// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintBelafonteDay (Belafonte Day) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Belafonte+Day
type TintBelafonteDay struct{}

// DisplayName returns the display name of the tint.
func (t *TintBelafonteDay) DisplayName() string {
	return "Belafonte Day"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintBelafonteDay) ID() string {
	return "belafonte_day"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintBelafonteDay) About() string {
	return `Tint: Belafonte Day`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintBelafonteDay) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#45373c")
}

// Bg returns the recommended default background color for this tint.
func (t *TintBelafonteDay) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#d5ccba")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintBelafonteDay) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintBelafonteDay) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintBelafonteDay) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#5e5252")
}

func (t *TintBelafonteDay) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#426a79")
}

func (t *TintBelafonteDay) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#989a9c")
}

func (t *TintBelafonteDay) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#858162")
}

func (t *TintBelafonteDay) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#97522c")
}

func (t *TintBelafonteDay) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#be100e")
}

func (t *TintBelafonteDay) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#d5ccba")
}

func (t *TintBelafonteDay) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#eaa549")
}

func (t *TintBelafonteDay) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#20111b")
}

func (t *TintBelafonteDay) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#426a79")
}

func (t *TintBelafonteDay) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#989a9c")
}

func (t *TintBelafonteDay) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#858162")
}

func (t *TintBelafonteDay) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#97522c")
}

func (t *TintBelafonteDay) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#be100e")
}

func (t *TintBelafonteDay) White() lipgloss.TerminalColor {
	return lipgloss.Color("#968c83")
}

func (t *TintBelafonteDay) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#eaa549")
}
