// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintBlueBerryPie (BlueBerryPie) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=BlueBerryPie
type TintBlueBerryPie struct{}

// DisplayName returns the display name of the tint.
func (t *TintBlueBerryPie) DisplayName() string {
	return "BlueBerryPie"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintBlueBerryPie) ID() string {
	return "blue_berry_pie"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintBlueBerryPie) About() string {
	return `Tint: BlueBerryPie`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintBlueBerryPie) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#babab9")
}

// Bg returns the recommended default background color for this tint.
func (t *TintBlueBerryPie) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#1c0c28")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintBlueBerryPie) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintBlueBerryPie) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintBlueBerryPie) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#201637")
}

func (t *TintBlueBerryPie) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#39173d")
}

func (t *TintBlueBerryPie) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#5e6071")
}

func (t *TintBlueBerryPie) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#0a6c7e")
}

func (t *TintBlueBerryPie) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#bc94b7")
}

func (t *TintBlueBerryPie) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#c87272")
}

func (t *TintBlueBerryPie) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#0a6c7e")
}

func (t *TintBlueBerryPie) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#7a3188")
}

func (t *TintBlueBerryPie) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#0a4c62")
}

func (t *TintBlueBerryPie) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#90a5bd")
}

func (t *TintBlueBerryPie) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#7e83cc")
}

func (t *TintBlueBerryPie) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#5cb1b3")
}

func (t *TintBlueBerryPie) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#9d54a7")
}

func (t *TintBlueBerryPie) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#99246e")
}

func (t *TintBlueBerryPie) White() lipgloss.TerminalColor {
	return lipgloss.Color("#f0e8d6")
}

func (t *TintBlueBerryPie) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#eab9a8")
}
