// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintCatppuccinMacchiato (Catppuccin Macchiato) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#CatppuccinMacchiato
type TintCatppuccinMacchiato struct{}

// DisplayName returns the display name of the tint.
func (t *TintCatppuccinMacchiato) DisplayName() string {
	return "Catppuccin Macchiato"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintCatppuccinMacchiato) ID() string {
	return "catppuccin_macchiato"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintCatppuccinMacchiato) About() string {
	return `Tint: Catppuccin Macchiato`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintCatppuccinMacchiato) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#cad3f5")
}

// Bg returns the recommended default background color for this tint.
func (t *TintCatppuccinMacchiato) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#24273a")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintCatppuccinMacchiato) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.Color("#5b6078")
}

// Cursor returns the recommended color for the cursor.
func (t *TintCatppuccinMacchiato) Cursor() lipgloss.TerminalColor {
	return lipgloss.Color("#f4dbd6")
}

func (t *TintCatppuccinMacchiato) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#5b6078")
}

func (t *TintCatppuccinMacchiato) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#8aadf4")
}

func (t *TintCatppuccinMacchiato) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#8bd5ca")
}

func (t *TintCatppuccinMacchiato) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#a6da95")
}

func (t *TintCatppuccinMacchiato) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#f5bde6")
}

func (t *TintCatppuccinMacchiato) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#ed8796")
}

func (t *TintCatppuccinMacchiato) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#b8c0e0")
}

func (t *TintCatppuccinMacchiato) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#eed49f")
}

func (t *TintCatppuccinMacchiato) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#494d64")
}

func (t *TintCatppuccinMacchiato) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#8aadf4")
}

func (t *TintCatppuccinMacchiato) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#8bd5ca")
}

func (t *TintCatppuccinMacchiato) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#a6da95")
}

func (t *TintCatppuccinMacchiato) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#f5bde6")
}

func (t *TintCatppuccinMacchiato) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#ed8796")
}

func (t *TintCatppuccinMacchiato) White() lipgloss.TerminalColor {
	return lipgloss.Color("#b8c0e0")
}

func (t *TintCatppuccinMacchiato) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#eed49f")
}
