// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintCyberpunk (cyberpunk) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#Cyberpunk
type TintCyberpunk struct{}

// DisplayName returns the display name of the tint.
func (t *TintCyberpunk) DisplayName() string {
	return "cyberpunk"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintCyberpunk) ID() string {
	return "cyberpunk"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintCyberpunk) About() string {
	return `Tint: cyberpunk`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintCyberpunk) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#e5e5e5")
}

// Bg returns the recommended default background color for this tint.
func (t *TintCyberpunk) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#332a57")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintCyberpunk) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintCyberpunk) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintCyberpunk) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintCyberpunk) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#1bccfd")
}

func (t *TintCyberpunk) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#99d6fc")
}

func (t *TintCyberpunk) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#21f6bc")
}

func (t *TintCyberpunk) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#e6aefe")
}

func (t *TintCyberpunk) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#ff8aa4")
}

func (t *TintCyberpunk) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintCyberpunk) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fff787")
}

func (t *TintCyberpunk) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintCyberpunk) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#00bfff")
}

func (t *TintCyberpunk) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#86cbfe")
}

func (t *TintCyberpunk) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#00fbac")
}

func (t *TintCyberpunk) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#df95ff")
}

func (t *TintCyberpunk) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#ff7092")
}

func (t *TintCyberpunk) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintCyberpunk) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fffa6a")
}
