// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintFahrenheit (Fahrenheit) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#Fahrenheit
type TintFahrenheit struct{}

// DisplayName returns the display name of the tint.
func (t *TintFahrenheit) DisplayName() string {
	return "Fahrenheit"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintFahrenheit) ID() string {
	return "fahrenheit"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintFahrenheit) About() string {
	return `Tint: Fahrenheit`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintFahrenheit) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffce")
}

// Bg returns the recommended default background color for this tint.
func (t *TintFahrenheit) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintFahrenheit) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintFahrenheit) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintFahrenheit) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintFahrenheit) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#cb4a05")
}

func (t *TintFahrenheit) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#fed04d")
}

func (t *TintFahrenheit) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#cc734d")
}

func (t *TintFahrenheit) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#4e739f")
}

func (t *TintFahrenheit) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#fecea0")
}

func (t *TintFahrenheit) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintFahrenheit) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fd9f4d")
}

func (t *TintFahrenheit) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#1d1d1d")
}

func (t *TintFahrenheit) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#720102")
}

func (t *TintFahrenheit) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#979797")
}

func (t *TintFahrenheit) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#9e744d")
}

func (t *TintFahrenheit) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#734c4d")
}

func (t *TintFahrenheit) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#cda074")
}

func (t *TintFahrenheit) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffce")
}

func (t *TintFahrenheit) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fecf75")
}
