// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintFloraverse (Floraverse) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#Floraverse
type TintFloraverse struct{}

// DisplayName returns the display name of the tint.
func (t *TintFloraverse) DisplayName() string {
	return "Floraverse"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintFloraverse) ID() string {
	return "floraverse"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintFloraverse) About() string {
	return `Tint: Floraverse`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintFloraverse) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#dbd1b9")
}

// Bg returns the recommended default background color for this tint.
func (t *TintFloraverse) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#0e0d15")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintFloraverse) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintFloraverse) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintFloraverse) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#331e4d")
}

func (t *TintFloraverse) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#40a4cf")
}

func (t *TintFloraverse) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#62caa8")
}

func (t *TintFloraverse) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#b4ce59")
}

func (t *TintFloraverse) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#f12aae")
}

func (t *TintFloraverse) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#d02063")
}

func (t *TintFloraverse) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#fff5db")
}

func (t *TintFloraverse) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fac357")
}

func (t *TintFloraverse) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#08002e")
}

func (t *TintFloraverse) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#1d6da1")
}

func (t *TintFloraverse) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#42a38c")
}

func (t *TintFloraverse) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#5d731a")
}

func (t *TintFloraverse) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#b7077e")
}

func (t *TintFloraverse) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#64002c")
}

func (t *TintFloraverse) White() lipgloss.TerminalColor {
	return lipgloss.Color("#f3e0b8")
}

func (t *TintFloraverse) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#cd751c")
}
