// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintFrontEndDelight (FrontEndDelight) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#FrontEndDelight
type TintFrontEndDelight struct{}

// DisplayName returns the display name of the tint.
func (t *TintFrontEndDelight) DisplayName() string {
	return "FrontEndDelight"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintFrontEndDelight) ID() string {
	return "front_end_delight"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintFrontEndDelight) About() string {
	return `Tint: FrontEndDelight`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintFrontEndDelight) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#adadad")
}

// Bg returns the recommended default background color for this tint.
func (t *TintFrontEndDelight) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#1b1c1d")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintFrontEndDelight) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintFrontEndDelight) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintFrontEndDelight) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#5fac6d")
}

func (t *TintFrontEndDelight) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#3393ca")
}

func (t *TintFrontEndDelight) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#4fbce6")
}

func (t *TintFrontEndDelight) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#74ec4c")
}

func (t *TintFrontEndDelight) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#e75e4f")
}

func (t *TintFrontEndDelight) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#f74319")
}

func (t *TintFrontEndDelight) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#8c735b")
}

func (t *TintFrontEndDelight) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fdc325")
}

func (t *TintFrontEndDelight) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#242526")
}

func (t *TintFrontEndDelight) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#2c70b7")
}

func (t *TintFrontEndDelight) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#3ca1a6")
}

func (t *TintFrontEndDelight) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#565747")
}

func (t *TintFrontEndDelight) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#f02e4f")
}

func (t *TintFrontEndDelight) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#f8511b")
}

func (t *TintFrontEndDelight) White() lipgloss.TerminalColor {
	return lipgloss.Color("#adadad")
}

func (t *TintFrontEndDelight) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fa771d")
}
