// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintGithub (Github) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Github
type TintGithub struct{}

// DisplayName returns the display name of the tint.
func (t *TintGithub) DisplayName() string {
	return "Github"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintGithub) ID() string {
	return "github"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintGithub) About() string {
	return `Tint: Github`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintGithub) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#3e3e3e")
}

// Bg returns the recommended default background color for this tint.
func (t *TintGithub) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#f4f4f4")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintGithub) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintGithub) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintGithub) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#666666")
}

func (t *TintGithub) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#2e6cba")
}

func (t *TintGithub) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#1cfafe")
}

func (t *TintGithub) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#87d5a2")
}

func (t *TintGithub) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#ffa29f")
}

func (t *TintGithub) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#de0000")
}

func (t *TintGithub) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintGithub) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#f1d007")
}

func (t *TintGithub) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#3e3e3e")
}

func (t *TintGithub) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#003e8a")
}

func (t *TintGithub) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#89d1ec")
}

func (t *TintGithub) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#07962a")
}

func (t *TintGithub) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#e94691")
}

func (t *TintGithub) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#970b16")
}

func (t *TintGithub) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintGithub) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#f8eec7")
}
