// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintHomebrew (Homebrew) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#Homebrew
type TintHomebrew struct{}

// DisplayName returns the display name of the tint.
func (t *TintHomebrew) DisplayName() string {
	return "Homebrew"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintHomebrew) ID() string {
	return "homebrew"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintHomebrew) About() string {
	return `Tint: Homebrew`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintHomebrew) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#00ff00")
}

// Bg returns the recommended default background color for this tint.
func (t *TintHomebrew) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintHomebrew) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintHomebrew) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintHomebrew) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#666666")
}

func (t *TintHomebrew) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#0000ff")
}

func (t *TintHomebrew) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#00e5e5")
}

func (t *TintHomebrew) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#00d900")
}

func (t *TintHomebrew) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#e500e5")
}

func (t *TintHomebrew) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#e50000")
}

func (t *TintHomebrew) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#e5e5e5")
}

func (t *TintHomebrew) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#e5e500")
}

func (t *TintHomebrew) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintHomebrew) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#0000b2")
}

func (t *TintHomebrew) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#00a6b2")
}

func (t *TintHomebrew) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#00a600")
}

func (t *TintHomebrew) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#b200b2")
}

func (t *TintHomebrew) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#990000")
}

func (t *TintHomebrew) White() lipgloss.TerminalColor {
	return lipgloss.Color("#bfbfbf")
}

func (t *TintHomebrew) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#999900")
}
