// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//
// Additional credit to:
//  * shivang (https://github.com/ShivangMathur1)

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintHyper (Hyper) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Hyper
//
// Credit to:
//   - shivang (https://github.com/ShivangMathur1)
type TintHyper struct{}

// DisplayName returns the display name of the tint.
func (t *TintHyper) DisplayName() string {
	return "Hyper"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintHyper) ID() string {
	return "hyper"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintHyper) About() string {
	return `Tint: Hyper
Tint credits:
  * shivang (https://github.com/ShivangMathur1)`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintHyper) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#FFFFFF")
}

// Bg returns the recommended default background color for this tint.
func (t *TintHyper) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintHyper) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.Color("#F81CE5")
}

// Cursor returns the recommended color for the cursor.
func (t *TintHyper) Cursor() lipgloss.TerminalColor {
	return lipgloss.Color("#FFFFFF")
}

func (t *TintHyper) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#808080")
}

func (t *TintHyper) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#0066FF")
}

func (t *TintHyper) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#00FFFF")
}

func (t *TintHyper) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#33FF00")
}

func (t *TintHyper) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#CC00FF")
}

func (t *TintHyper) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#FE0100")
}

func (t *TintHyper) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#FFFFFF")
}

func (t *TintHyper) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#FEFF00")
}

func (t *TintHyper) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintHyper) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#0066FF")
}

func (t *TintHyper) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#00FFFF")
}

func (t *TintHyper) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#33FF00")
}

func (t *TintHyper) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#CC00FF")
}

func (t *TintHyper) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#FE0100")
}

func (t *TintHyper) White() lipgloss.TerminalColor {
	return lipgloss.Color("#D0D0D0")
}

func (t *TintHyper) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#FEFF00")
}
