// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintIdleToes (idleToes) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#IdleToes
type TintIdleToes struct{}

// DisplayName returns the display name of the tint.
func (t *TintIdleToes) DisplayName() string {
	return "idleToes"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintIdleToes) ID() string {
	return "idle_toes"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintIdleToes) About() string {
	return `Tint: idleToes`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintIdleToes) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintIdleToes) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#323232")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintIdleToes) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintIdleToes) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintIdleToes) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#535353")
}

func (t *TintIdleToes) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#5eb7f7")
}

func (t *TintIdleToes) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#dcf4ff")
}

func (t *TintIdleToes) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#9dff91")
}

func (t *TintIdleToes) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#ff9dff")
}

func (t *TintIdleToes) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#f07070")
}

func (t *TintIdleToes) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintIdleToes) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffe48b")
}

func (t *TintIdleToes) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#323232")
}

func (t *TintIdleToes) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#4099ff")
}

func (t *TintIdleToes) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#bed6ff")
}

func (t *TintIdleToes) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#7fe173")
}

func (t *TintIdleToes) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#f680ff")
}

func (t *TintIdleToes) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#d25252")
}

func (t *TintIdleToes) White() lipgloss.TerminalColor {
	return lipgloss.Color("#eeeeec")
}

func (t *TintIdleToes) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffc66d")
}
