// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintIRBlack (IR_Black) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#IRBlack
type TintIRBlack struct{}

// DisplayName returns the display name of the tint.
func (t *TintIRBlack) DisplayName() string {
	return "IR_Black"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintIRBlack) ID() string {
	return "ir_black"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintIRBlack) About() string {
	return `Tint: IR_Black`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintIRBlack) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#f1f1f1")
}

// Bg returns the recommended default background color for this tint.
func (t *TintIRBlack) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintIRBlack) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintIRBlack) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintIRBlack) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#7b7b7b")
}

func (t *TintIRBlack) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#b5dcff")
}

func (t *TintIRBlack) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#e0e0fe")
}

func (t *TintIRBlack) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#cfffab")
}

func (t *TintIRBlack) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#fb9cfe")
}

func (t *TintIRBlack) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#fcb6b0")
}

func (t *TintIRBlack) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintIRBlack) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffcc")
}

func (t *TintIRBlack) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#4f4f4f")
}

func (t *TintIRBlack) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#96cafe")
}

func (t *TintIRBlack) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#c6c5fe")
}

func (t *TintIRBlack) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#a8ff60")
}

func (t *TintIRBlack) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#fa73fd")
}

func (t *TintIRBlack) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#fa6c60")
}

func (t *TintIRBlack) White() lipgloss.TerminalColor {
	return lipgloss.Color("#efedef")
}

func (t *TintIRBlack) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fffeb7")
}
