// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintKanagawa (Kanagawa) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#Kanagawa
type TintKanagawa struct{}

// DisplayName returns the display name of the tint.
func (t *TintKanagawa) DisplayName() string {
	return "Kanagawa"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintKanagawa) ID() string {
	return "kanagawa"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintKanagawa) About() string {
	return `Tint: Kanagawa`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintKanagawa) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#DCD7BA")
}

// Bg returns the recommended default background color for this tint.
func (t *TintKanagawa) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#1F1F28")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintKanagawa) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.Color("#2A2A37")
}

// Cursor returns the recommended color for the cursor.
func (t *TintKanagawa) Cursor() lipgloss.TerminalColor {
	return lipgloss.Color("#DCD7BA")
}

func (t *TintKanagawa) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#2A2A37")
}

func (t *TintKanagawa) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#7FB4CA")
}

func (t *TintKanagawa) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#A3D4D5")
}

func (t *TintKanagawa) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#98BB6C")
}

func (t *TintKanagawa) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#D27E99")
}

func (t *TintKanagawa) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#FF5D62")
}

func (t *TintKanagawa) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#DCD7BA")
}

func (t *TintKanagawa) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#E6C384")
}

func (t *TintKanagawa) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#1F1F28")
}

func (t *TintKanagawa) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#658594")
}

func (t *TintKanagawa) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#9CABCA")
}

func (t *TintKanagawa) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#76946A")
}

func (t *TintKanagawa) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#957FB8")
}

func (t *TintKanagawa) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#E82424")
}

func (t *TintKanagawa) White() lipgloss.TerminalColor {
	return lipgloss.Color("#DCD7BA")
}

func (t *TintKanagawa) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#FF9E3B")
}
