// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintMaterialDarker (MaterialDarker) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#MaterialDarker
type TintMaterialDarker struct{}

// DisplayName returns the display name of the tint.
func (t *TintMaterialDarker) DisplayName() string {
	return "MaterialDarker"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintMaterialDarker) ID() string {
	return "material_darker"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintMaterialDarker) About() string {
	return `Tint: MaterialDarker`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintMaterialDarker) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#eeffff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintMaterialDarker) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#212121")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintMaterialDarker) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintMaterialDarker) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintMaterialDarker) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#545454")
}

func (t *TintMaterialDarker) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#82aaff")
}

func (t *TintMaterialDarker) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#89ddff")
}

func (t *TintMaterialDarker) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#c3e88d")
}

func (t *TintMaterialDarker) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#c792ea")
}

func (t *TintMaterialDarker) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#ff5370")
}

func (t *TintMaterialDarker) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintMaterialDarker) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffcb6b")
}

func (t *TintMaterialDarker) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintMaterialDarker) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#82aaff")
}

func (t *TintMaterialDarker) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#89ddff")
}

func (t *TintMaterialDarker) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#c3e88d")
}

func (t *TintMaterialDarker) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#c792ea")
}

func (t *TintMaterialDarker) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#ff5370")
}

func (t *TintMaterialDarker) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintMaterialDarker) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffcb6b")
}
