// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintMaterialDark (MaterialDark) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#MaterialDark
type TintMaterialDark struct{}

// DisplayName returns the display name of the tint.
func (t *TintMaterialDark) DisplayName() string {
	return "MaterialDark"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintMaterialDark) ID() string {
	return "material_dark"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintMaterialDark) About() string {
	return `Tint: MaterialDark`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintMaterialDark) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#e5e5e5")
}

// Bg returns the recommended default background color for this tint.
func (t *TintMaterialDark) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#232322")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintMaterialDark) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintMaterialDark) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintMaterialDark) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#424242")
}

func (t *TintMaterialDark) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#54a4f3")
}

func (t *TintMaterialDark) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#26bbd1")
}

func (t *TintMaterialDark) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#7aba3a")
}

func (t *TintMaterialDark) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#aa4dbc")
}

func (t *TintMaterialDark) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#e83b3f")
}

func (t *TintMaterialDark) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#d9d9d9")
}

func (t *TintMaterialDark) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffea2e")
}

func (t *TintMaterialDark) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#212121")
}

func (t *TintMaterialDark) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#134eb2")
}

func (t *TintMaterialDark) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#0e717c")
}

func (t *TintMaterialDark) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#457b24")
}

func (t *TintMaterialDark) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#560088")
}

func (t *TintMaterialDark) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#b7141f")
}

func (t *TintMaterialDark) White() lipgloss.TerminalColor {
	return lipgloss.Color("#efefef")
}

func (t *TintMaterialDark) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#f6981e")
}
