// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintPaleNightHc (PaleNightHC) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#PaleNightHc
type TintPaleNightHc struct{}

// DisplayName returns the display name of the tint.
func (t *TintPaleNightHc) DisplayName() string {
	return "PaleNightHC"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintPaleNightHc) ID() string {
	return "pale_night_hc"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintPaleNightHc) About() string {
	return `Tint: PaleNightHC`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintPaleNightHc) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#cccccc")
}

// Bg returns the recommended default background color for this tint.
func (t *TintPaleNightHc) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#3e4251")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintPaleNightHc) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintPaleNightHc) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintPaleNightHc) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#666666")
}

func (t *TintPaleNightHc) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#b4ccff")
}

func (t *TintPaleNightHc) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#b8eaff")
}

func (t *TintPaleNightHc) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#dbf1ba")
}

func (t *TintPaleNightHc) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#ddbdf2")
}

func (t *TintPaleNightHc) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#f6a9ae")
}

func (t *TintPaleNightHc) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#999999")
}

func (t *TintPaleNightHc) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffdfa6")
}

func (t *TintPaleNightHc) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintPaleNightHc) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#82aaff")
}

func (t *TintPaleNightHc) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#89ddff")
}

func (t *TintPaleNightHc) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#c3e88d")
}

func (t *TintPaleNightHc) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#c792ea")
}

func (t *TintPaleNightHc) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#f07178")
}

func (t *TintPaleNightHc) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintPaleNightHc) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffcb6b")
}
