// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes
//
// Additional credit to:
//  * Chrissy LeMaire (https://github.com/potatoqualitee)

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintRetrowave (Retrowave) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#Retrowave
//
// Credit to:
//   - Chrissy LeMaire (https://github.com/potatoqualitee)
type TintRetrowave struct{}

// DisplayName returns the display name of the tint.
func (t *TintRetrowave) DisplayName() string {
	return "Retrowave"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintRetrowave) ID() string {
	return "retrowave"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintRetrowave) About() string {
	return `Tint: Retrowave
Tint credits:
  * Chrissy LeMaire (https://github.com/potatoqualitee)`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintRetrowave) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#46BDFF")
}

// Bg returns the recommended default background color for this tint.
func (t *TintRetrowave) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#070825")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintRetrowave) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintRetrowave) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintRetrowave) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#FF16B0")
}

func (t *TintRetrowave) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#46BDFF")
}

func (t *TintRetrowave) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#ff901f")
}

func (t *TintRetrowave) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#fcee54")
}

func (t *TintRetrowave) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#FF92DF")
}

func (t *TintRetrowave) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#f85353")
}

func (t *TintRetrowave) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintRetrowave) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintRetrowave) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#181A1F")
}

func (t *TintRetrowave) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#46BDFF")
}

func (t *TintRetrowave) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#df81fc")
}

func (t *TintRetrowave) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#929292")
}

func (t *TintRetrowave) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#FF92DF")
}

func (t *TintRetrowave) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#FF16B0")
}

func (t *TintRetrowave) White() lipgloss.TerminalColor {
	return lipgloss.Color("#FFFFFF")
}

func (t *TintRetrowave) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fcee54")
}
