// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes
//
// Additional credit to:
//  * d-mckee (https://github.com/d-mckee)

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintSonoranGothic (Sonoran Gothic) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#SonoranGothic
//
// Credit to:
//   - d-mckee (https://github.com/d-mckee)
type TintSonoranGothic struct{}

// DisplayName returns the display name of the tint.
func (t *TintSonoranGothic) DisplayName() string {
	return "Sonoran Gothic"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintSonoranGothic) ID() string {
	return "sonoran_gothic"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintSonoranGothic) About() string {
	return `Tint: Sonoran Gothic
Tint credits:
  * d-mckee (https://github.com/d-mckee)`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintSonoranGothic) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#EAF4DE")
}

// Bg returns the recommended default background color for this tint.
func (t *TintSonoranGothic) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#241F17")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintSonoranGothic) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintSonoranGothic) Cursor() lipgloss.TerminalColor {
	return lipgloss.Color("#EAF4DE")
}

func (t *TintSonoranGothic) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#867F6E")
}

func (t *TintSonoranGothic) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#227B4D")
}

func (t *TintSonoranGothic) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#E18F62")
}

func (t *TintSonoranGothic) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#669C50")
}

func (t *TintSonoranGothic) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#A5ABDA")
}

func (t *TintSonoranGothic) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#EB6f6f")
}

func (t *TintSonoranGothic) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#EAF4DE")
}

func (t *TintSonoranGothic) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#F2D696")
}

func (t *TintSonoranGothic) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#867F6E")
}

func (t *TintSonoranGothic) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#227B4d")
}

func (t *TintSonoranGothic) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#E18F62")
}

func (t *TintSonoranGothic) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#669C50")
}

func (t *TintSonoranGothic) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#A5ABDA")
}

func (t *TintSonoranGothic) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#EB6f6f")
}

func (t *TintSonoranGothic) White() lipgloss.TerminalColor {
	return lipgloss.Color("#EAF4DE")
}

func (t *TintSonoranGothic) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#F2D696")
}
