// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintSpaceGrayEighties (SpaceGray Eighties) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#SpaceGrayEighties
type TintSpaceGrayEighties struct{}

// DisplayName returns the display name of the tint.
func (t *TintSpaceGrayEighties) DisplayName() string {
	return "SpaceGray Eighties"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintSpaceGrayEighties) ID() string {
	return "space_gray_eighties"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintSpaceGrayEighties) About() string {
	return `Tint: SpaceGray Eighties`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintSpaceGrayEighties) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#bdbaae")
}

// Bg returns the recommended default background color for this tint.
func (t *TintSpaceGrayEighties) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#222222")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintSpaceGrayEighties) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintSpaceGrayEighties) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintSpaceGrayEighties) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#555555")
}

func (t *TintSpaceGrayEighties) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#4d84d1")
}

func (t *TintSpaceGrayEighties) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#83e9e4")
}

func (t *TintSpaceGrayEighties) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#93d493")
}

func (t *TintSpaceGrayEighties) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#ff55ff")
}

func (t *TintSpaceGrayEighties) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#ff6973")
}

func (t *TintSpaceGrayEighties) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintSpaceGrayEighties) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffd256")
}

func (t *TintSpaceGrayEighties) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#15171c")
}

func (t *TintSpaceGrayEighties) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#5486c0")
}

func (t *TintSpaceGrayEighties) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#57c2c1")
}

func (t *TintSpaceGrayEighties) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#81a764")
}

func (t *TintSpaceGrayEighties) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#bf83c1")
}

func (t *TintSpaceGrayEighties) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#ec5f67")
}

func (t *TintSpaceGrayEighties) White() lipgloss.TerminalColor {
	return lipgloss.Color("#efece7")
}

func (t *TintSpaceGrayEighties) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fec254")
}
