// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintSpring (Spring) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Spring
type TintSpring struct{}

// DisplayName returns the display name of the tint.
func (t *TintSpring) DisplayName() string {
	return "Spring"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintSpring) ID() string {
	return "spring"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintSpring) About() string {
	return `Tint: Spring`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintSpring) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#4d4d4c")
}

// Bg returns the recommended default background color for this tint.
func (t *TintSpring) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintSpring) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintSpring) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintSpring) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintSpring) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#15a9fd")
}

func (t *TintSpring) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#3e999f")
}

func (t *TintSpring) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#1fc231")
}

func (t *TintSpring) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#8959a8")
}

func (t *TintSpring) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#ff0021")
}

func (t *TintSpring) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintSpring) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#d5b807")
}

func (t *TintSpring) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintSpring) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#1dd3ee")
}

func (t *TintSpring) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#3e999f")
}

func (t *TintSpring) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#1f8c3b")
}

func (t *TintSpring) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#8959a8")
}

func (t *TintSpring) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#ff4d83")
}

func (t *TintSpring) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintSpring) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#1fc95b")
}
