// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintSynthwave (synthwave) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=synthwave
type TintSynthwave struct{}

// DisplayName returns the display name of the tint.
func (t *TintSynthwave) DisplayName() string {
	return "synthwave"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintSynthwave) ID() string {
	return "synthwave"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintSynthwave) About() string {
	return `Tint: synthwave`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintSynthwave) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#dad9c7")
}

// Bg returns the recommended default background color for this tint.
func (t *TintSynthwave) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintSynthwave) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintSynthwave) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintSynthwave) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintSynthwave) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#2f9ded")
}

func (t *TintSynthwave) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#19cde6")
}

func (t *TintSynthwave) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#25c141")
}

func (t *TintSynthwave) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#f97137")
}

func (t *TintSynthwave) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#f841a0")
}

func (t *TintSynthwave) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintSynthwave) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fdf454")
}

func (t *TintSynthwave) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintSynthwave) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#2186ec")
}

func (t *TintSynthwave) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#12c3e2")
}

func (t *TintSynthwave) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#1ebb2b")
}

func (t *TintSynthwave) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#f85a21")
}

func (t *TintSynthwave) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#f6188f")
}

func (t *TintSynthwave) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintSynthwave) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#fdf834")
}
