// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintTinaciousDesignDark (Tinacious Design (Dark)) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Tinacious+Design+%28Dark%29
type TintTinaciousDesignDark struct{}

// DisplayName returns the display name of the tint.
func (t *TintTinaciousDesignDark) DisplayName() string {
	return "Tinacious Design (Dark)"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintTinaciousDesignDark) ID() string {
	return "tinacious_design_dark"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintTinaciousDesignDark) About() string {
	return `Tint: Tinacious Design (Dark)`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintTinaciousDesignDark) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#cbcbf0")
}

// Bg returns the recommended default background color for this tint.
func (t *TintTinaciousDesignDark) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#1d1d26")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintTinaciousDesignDark) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintTinaciousDesignDark) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintTinaciousDesignDark) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#636667")
}

func (t *TintTinaciousDesignDark) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#00cbff")
}

func (t *TintTinaciousDesignDark) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#00d5d4")
}

func (t *TintTinaciousDesignDark) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#00d364")
}

func (t *TintTinaciousDesignDark) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#d783ff")
}

func (t *TintTinaciousDesignDark) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#ff2f92")
}

func (t *TintTinaciousDesignDark) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#d5d6f3")
}

func (t *TintTinaciousDesignDark) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffd479")
}

func (t *TintTinaciousDesignDark) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#1d1d26")
}

func (t *TintTinaciousDesignDark) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#00cbff")
}

func (t *TintTinaciousDesignDark) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#00ceca")
}

func (t *TintTinaciousDesignDark) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#00d364")
}

func (t *TintTinaciousDesignDark) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#cc66ff")
}

func (t *TintTinaciousDesignDark) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#ff3399")
}

func (t *TintTinaciousDesignDark) White() lipgloss.TerminalColor {
	return lipgloss.Color("#cbcbf0")
}

func (t *TintTinaciousDesignDark) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffcc66")
}
