// Copyright (c) Liam Stanley <liam@liam.sh>. All rights reserved. Use of
// this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintTomorrowNightBlue (Tomorrow Night Blue) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#TomorrowNightBlue
type TintTomorrowNightBlue struct{}

// DisplayName returns the display name of the tint.
func (t *TintTomorrowNightBlue) DisplayName() string {
	return "Tomorrow Night Blue"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintTomorrowNightBlue) ID() string {
	return "tomorrow_night_blue"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintTomorrowNightBlue) About() string {
	return `Tint: Tomorrow Night Blue`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintTomorrowNightBlue) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintTomorrowNightBlue) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#002451")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintTomorrowNightBlue) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintTomorrowNightBlue) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintTomorrowNightBlue) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintTomorrowNightBlue) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#bbdaff")
}

func (t *TintTomorrowNightBlue) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#99ffff")
}

func (t *TintTomorrowNightBlue) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#d1f1a9")
}

func (t *TintTomorrowNightBlue) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#ebbbff")
}

func (t *TintTomorrowNightBlue) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#ff9da4")
}

func (t *TintTomorrowNightBlue) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintTomorrowNightBlue) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffeead")
}

func (t *TintTomorrowNightBlue) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintTomorrowNightBlue) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#bbdaff")
}

func (t *TintTomorrowNightBlue) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#99ffff")
}

func (t *TintTomorrowNightBlue) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#d1f1a9")
}

func (t *TintTomorrowNightBlue) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#ebbbff")
}

func (t *TintTomorrowNightBlue) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#ff9da4")
}

func (t *TintTomorrowNightBlue) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintTomorrowNightBlue) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#ffeead")
}
