// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// All tints can be previewed here:
//  * https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes
//  * https://github.com/mbadolato/iTerm2-Color-Schemes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintVaughn (Vaughn) is a collection of lipgloss styles.
//
// Reference: https://github.com/lrstanley/bubbletint/blob/master/DEFAULT_TINTS.md#Vaughn
type TintVaughn struct{}

// DisplayName returns the display name of the tint.
func (t *TintVaughn) DisplayName() string {
	return "Vaughn"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintVaughn) ID() string {
	return "vaughn"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintVaughn) About() string {
	return `Tint: Vaughn`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintVaughn) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#dcdccc")
}

// Bg returns the recommended default background color for this tint.
func (t *TintVaughn) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#25234f")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintVaughn) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintVaughn) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintVaughn) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#709080")
}

func (t *TintVaughn) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#5555ff")
}

func (t *TintVaughn) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#93e0e3")
}

func (t *TintVaughn) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#60b48a")
}

func (t *TintVaughn) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#ec93d3")
}

func (t *TintVaughn) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#dca3a3")
}

func (t *TintVaughn) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintVaughn) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#f0dfaf")
}

func (t *TintVaughn) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#25234f")
}

func (t *TintVaughn) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#5555ff")
}

func (t *TintVaughn) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#8cd0d3")
}

func (t *TintVaughn) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#60b48a")
}

func (t *TintVaughn) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#f08cc3")
}

func (t *TintVaughn) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#705050")
}

func (t *TintVaughn) White() lipgloss.TerminalColor {
	return lipgloss.Color("#709080")
}

func (t *TintVaughn) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#dfaf8f")
}
