// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintVioletDark (Violet Dark) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Violet+Dark
type TintVioletDark struct{}

// DisplayName returns the display name of the tint.
func (t *TintVioletDark) DisplayName() string {
	return "Violet Dark"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintVioletDark) ID() string {
	return "violet_dark"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintVioletDark) About() string {
	return `Tint: Violet Dark`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintVioletDark) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#708284")
}

// Bg returns the recommended default background color for this tint.
func (t *TintVioletDark) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#1c1d1f")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintVioletDark) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintVioletDark) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintVioletDark) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#45484b")
}

func (t *TintVioletDark) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#2176c7")
}

func (t *TintVioletDark) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#259286")
}

func (t *TintVioletDark) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#738a04")
}

func (t *TintVioletDark) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#c61c6f")
}

func (t *TintVioletDark) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#bd3613")
}

func (t *TintVioletDark) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#c9c6bd")
}

func (t *TintVioletDark) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#a57705")
}

func (t *TintVioletDark) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#56595c")
}

func (t *TintVioletDark) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#2e8bce")
}

func (t *TintVioletDark) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#32a198")
}

func (t *TintVioletDark) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#85981c")
}

func (t *TintVioletDark) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#d13a82")
}

func (t *TintVioletDark) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#c94c22")
}

func (t *TintVioletDark) White() lipgloss.TerminalColor {
	return lipgloss.Color("#c9c6bd")
}

func (t *TintVioletDark) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#b4881d")
}
