// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package defaulttints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintWryan (Wryan) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Wryan
type TintWryan struct{}

// DisplayName returns the display name of the tint.
func (t *TintWryan) DisplayName() string {
	return "Wryan"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintWryan) ID() string {
	return "wryan"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintWryan) About() string {
	return `Tint: Wryan`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintWryan) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#999993")
}

// Bg returns the recommended default background color for this tint.
func (t *TintWryan) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#101010")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintWryan) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintWryan) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintWryan) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#3d3d3d")
}

func (t *TintWryan) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#477ab3")
}

func (t *TintWryan) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#6096bf")
}

func (t *TintWryan) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#53a6a6")
}

func (t *TintWryan) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#7e62b3")
}

func (t *TintWryan) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#bf4d80")
}

func (t *TintWryan) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#c0c0c0")
}

func (t *TintWryan) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#9e9ecb")
}

func (t *TintWryan) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#333333")
}

func (t *TintWryan) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#395573")
}

func (t *TintWryan) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#31658c")
}

func (t *TintWryan) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#287373")
}

func (t *TintWryan) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#5e468c")
}

func (t *TintWryan) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#8c4665")
}

func (t *TintWryan) White() lipgloss.TerminalColor {
	return lipgloss.Color("#899ca1")
}

func (t *TintWryan) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#7c7c99")
}
