// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// Tint3024Night (3024 Night) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=3024+Night
type Tint3024Night struct{}

// DisplayName returns the display name of the tint.
func (t *Tint3024Night) DisplayName() string {
	return "3024 Night"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *Tint3024Night) ID() string {
	return "3024_night"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *Tint3024Night) About() string {
	return `Tint: 3024 Night`
}

// Fg returns the recommended default foreground color for this tint.
func (t *Tint3024Night) Fg() lipgloss.Color {
	return lipgloss.Color("#a5a2a2")
}

// Bg returns the recommended default background color for this tint.
func (t *Tint3024Night) Bg() lipgloss.Color {
	return lipgloss.Color("#090300")
}

// SelectionBg returns the recommended background color for selected text.
func (t *Tint3024Night) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *Tint3024Night) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *Tint3024Night) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#5c5855")
}

func (t *Tint3024Night) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#807d7c")
}

func (t *Tint3024Night) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#cdab53")
}

func (t *Tint3024Night) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#3a3432")
}

func (t *Tint3024Night) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#d6d5d4")
}

func (t *Tint3024Night) BrightRed() lipgloss.Color {
	return lipgloss.Color("#e8bbd0")
}

func (t *Tint3024Night) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#f7f7f7")
}

func (t *Tint3024Night) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#4a4543")
}

func (t *Tint3024Night) Black() lipgloss.Color {
	return lipgloss.Color("#090300")
}

func (t *Tint3024Night) Blue() lipgloss.Color {
	return lipgloss.Color("#01a0e4")
}

func (t *Tint3024Night) Cyan() lipgloss.Color {
	return lipgloss.Color("#b5e4f4")
}

func (t *Tint3024Night) Green() lipgloss.Color {
	return lipgloss.Color("#01a252")
}

func (t *Tint3024Night) Purple() lipgloss.Color {
	return lipgloss.Color("#a16a94")
}

func (t *Tint3024Night) Red() lipgloss.Color {
	return lipgloss.Color("#db2d20")
}

func (t *Tint3024Night) White() lipgloss.Color {
	return lipgloss.Color("#a5a2a2")
}

func (t *Tint3024Night) Yellow() lipgloss.Color {
	return lipgloss.Color("#fded02")
}
