// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintAdventure (Adventure) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Adventure
type TintAdventure struct{}

// DisplayName returns the display name of the tint.
func (t *TintAdventure) DisplayName() string {
	return "Adventure"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintAdventure) ID() string {
	return "adventure"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintAdventure) About() string {
	return `Tint: Adventure`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintAdventure) Fg() lipgloss.Color {
	return lipgloss.Color("#feffff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintAdventure) Bg() lipgloss.Color {
	return lipgloss.Color("#040404")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintAdventure) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintAdventure) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintAdventure) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#685656")
}

func (t *TintAdventure) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#97d7ef")
}

func (t *TintAdventure) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#bdcfe5")
}

func (t *TintAdventure) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#99b52c")
}

func (t *TintAdventure) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#aa7900")
}

func (t *TintAdventure) BrightRed() lipgloss.Color {
	return lipgloss.Color("#d76b42")
}

func (t *TintAdventure) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#e4d5c7")
}

func (t *TintAdventure) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffb670")
}

func (t *TintAdventure) Black() lipgloss.Color {
	return lipgloss.Color("#040404")
}

func (t *TintAdventure) Blue() lipgloss.Color {
	return lipgloss.Color("#417ab3")
}

func (t *TintAdventure) Cyan() lipgloss.Color {
	return lipgloss.Color("#bdcfe5")
}

func (t *TintAdventure) Green() lipgloss.Color {
	return lipgloss.Color("#5da602")
}

func (t *TintAdventure) Purple() lipgloss.Color {
	return lipgloss.Color("#e5c499")
}

func (t *TintAdventure) Red() lipgloss.Color {
	return lipgloss.Color("#d84a33")
}

func (t *TintAdventure) White() lipgloss.Color {
	return lipgloss.Color("#dbded8")
}

func (t *TintAdventure) Yellow() lipgloss.Color {
	return lipgloss.Color("#eebb6e")
}
