// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintArthur (Arthur) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Arthur
type TintArthur struct{}

// DisplayName returns the display name of the tint.
func (t *TintArthur) DisplayName() string {
	return "Arthur"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintArthur) ID() string {
	return "arthur"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintArthur) About() string {
	return `Tint: Arthur`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintArthur) Fg() lipgloss.Color {
	return lipgloss.Color("#ddeedd")
}

// Bg returns the recommended default background color for this tint.
func (t *TintArthur) Bg() lipgloss.Color {
	return lipgloss.Color("#1c1c1c")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintArthur) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintArthur) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintArthur) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#554444")
}

func (t *TintArthur) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#87ceeb")
}

func (t *TintArthur) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#b0c4de")
}

func (t *TintArthur) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#88aa22")
}

func (t *TintArthur) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#996600")
}

func (t *TintArthur) BrightRed() lipgloss.Color {
	return lipgloss.Color("#cc5533")
}

func (t *TintArthur) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ddccbb")
}

func (t *TintArthur) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffa75d")
}

func (t *TintArthur) Black() lipgloss.Color {
	return lipgloss.Color("#3d352a")
}

func (t *TintArthur) Blue() lipgloss.Color {
	return lipgloss.Color("#6495ed")
}

func (t *TintArthur) Cyan() lipgloss.Color {
	return lipgloss.Color("#b0c4de")
}

func (t *TintArthur) Green() lipgloss.Color {
	return lipgloss.Color("#86af80")
}

func (t *TintArthur) Purple() lipgloss.Color {
	return lipgloss.Color("#deb887")
}

func (t *TintArthur) Red() lipgloss.Color {
	return lipgloss.Color("#cd5c5c")
}

func (t *TintArthur) White() lipgloss.Color {
	return lipgloss.Color("#bbaa99")
}

func (t *TintArthur) Yellow() lipgloss.Color {
	return lipgloss.Color("#e8ae5b")
}
