// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintBlulocoDark (BlulocoDark) is a collection of lipgloss styles.
type TintBlulocoDark struct{}

// DisplayName returns the display name of the tint.
func (t *TintBlulocoDark) DisplayName() string {
	return "BlulocoDark"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintBlulocoDark) ID() string {
	return "bluloco_dark"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintBlulocoDark) About() string {
	return `Tint: BlulocoDark`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintBlulocoDark) Fg() lipgloss.Color {
	return lipgloss.Color("#abb2bf")
}

// Bg returns the recommended default background color for this tint.
func (t *TintBlulocoDark) Bg() lipgloss.Color {
	return lipgloss.Color("#1e2127")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintBlulocoDark) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintBlulocoDark) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintBlulocoDark) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#61697a")
}

func (t *TintBlulocoDark) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#199ffd")
}

func (t *TintBlulocoDark) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#50acae")
}

func (t *TintBlulocoDark) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#37bd58")
}

func (t *TintBlulocoDark) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#fc58f6")
}

func (t *TintBlulocoDark) BrightRed() lipgloss.Color {
	return lipgloss.Color("#fc4a6d")
}

func (t *TintBlulocoDark) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintBlulocoDark) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#f6be48")
}

func (t *TintBlulocoDark) Black() lipgloss.Color {
	return lipgloss.Color("#4a505d")
}

func (t *TintBlulocoDark) Blue() lipgloss.Color {
	return lipgloss.Color("#285bff")
}

func (t *TintBlulocoDark) Cyan() lipgloss.Color {
	return lipgloss.Color("#366f9a")
}

func (t *TintBlulocoDark) Green() lipgloss.Color {
	return lipgloss.Color("#23974a")
}

func (t *TintBlulocoDark) Purple() lipgloss.Color {
	return lipgloss.Color("#8c62fd")
}

func (t *TintBlulocoDark) Red() lipgloss.Color {
	return lipgloss.Color("#f81141")
}

func (t *TintBlulocoDark) White() lipgloss.Color {
	return lipgloss.Color("#ccd5e5")
}

func (t *TintBlulocoDark) Yellow() lipgloss.Color {
	return lipgloss.Color("#fd7e57")
}
