// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintC64 (C64) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=C64
type TintC64 struct{}

// DisplayName returns the display name of the tint.
func (t *TintC64) DisplayName() string {
	return "C64"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintC64) ID() string {
	return "c_64"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintC64) About() string {
	return `Tint: C64`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintC64) Fg() lipgloss.Color {
	return lipgloss.Color("#7869c4")
}

// Bg returns the recommended default background color for this tint.
func (t *TintC64) Bg() lipgloss.Color {
	return lipgloss.Color("#40318d")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintC64) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintC64) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintC64) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintC64) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#40318d")
}

func (t *TintC64) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#67b6bd")
}

func (t *TintC64) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#55a049")
}

func (t *TintC64) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#8b3f96")
}

func (t *TintC64) BrightRed() lipgloss.Color {
	return lipgloss.Color("#883932")
}

func (t *TintC64) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#f7f7f7")
}

func (t *TintC64) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#bfce72")
}

func (t *TintC64) Black() lipgloss.Color {
	return lipgloss.Color("#090300")
}

func (t *TintC64) Blue() lipgloss.Color {
	return lipgloss.Color("#40318d")
}

func (t *TintC64) Cyan() lipgloss.Color {
	return lipgloss.Color("#67b6bd")
}

func (t *TintC64) Green() lipgloss.Color {
	return lipgloss.Color("#55a049")
}

func (t *TintC64) Purple() lipgloss.Color {
	return lipgloss.Color("#8b3f96")
}

func (t *TintC64) Red() lipgloss.Color {
	return lipgloss.Color("#883932")
}

func (t *TintC64) White() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintC64) Yellow() lipgloss.Color {
	return lipgloss.Color("#bfce72")
}
