// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintChalk (Chalk) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Chalk
type TintChalk struct{}

// DisplayName returns the display name of the tint.
func (t *TintChalk) DisplayName() string {
	return "Chalk"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintChalk) ID() string {
	return "chalk"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintChalk) About() string {
	return `Tint: Chalk`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintChalk) Fg() lipgloss.Color {
	return lipgloss.Color("#d2d8d9")
}

// Bg returns the recommended default background color for this tint.
func (t *TintChalk) Bg() lipgloss.Color {
	return lipgloss.Color("#2b2d2e")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintChalk) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintChalk) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintChalk) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#888888")
}

func (t *TintChalk) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#4196ff")
}

func (t *TintChalk) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#53cdbd")
}

func (t *TintChalk) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#80c470")
}

func (t *TintChalk) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#fc5275")
}

func (t *TintChalk) BrightRed() lipgloss.Color {
	return lipgloss.Color("#f24840")
}

func (t *TintChalk) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#d2d8d9")
}

func (t *TintChalk) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffeb62")
}

func (t *TintChalk) Black() lipgloss.Color {
	return lipgloss.Color("#7d8b8f")
}

func (t *TintChalk) Blue() lipgloss.Color {
	return lipgloss.Color("#2a7fac")
}

func (t *TintChalk) Cyan() lipgloss.Color {
	return lipgloss.Color("#44a799")
}

func (t *TintChalk) Green() lipgloss.Color {
	return lipgloss.Color("#789b6a")
}

func (t *TintChalk) Purple() lipgloss.Color {
	return lipgloss.Color("#bd4f5a")
}

func (t *TintChalk) Red() lipgloss.Color {
	return lipgloss.Color("#b23a52")
}

func (t *TintChalk) White() lipgloss.Color {
	return lipgloss.Color("#d2d8d9")
}

func (t *TintChalk) Yellow() lipgloss.Color {
	return lipgloss.Color("#b9ac4a")
}
