// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintChallengerDeep (ChallengerDeep) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=ChallengerDeep
type TintChallengerDeep struct{}

// DisplayName returns the display name of the tint.
func (t *TintChallengerDeep) DisplayName() string {
	return "ChallengerDeep"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintChallengerDeep) ID() string {
	return "challenger_deep"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintChallengerDeep) About() string {
	return `Tint: ChallengerDeep`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintChallengerDeep) Fg() lipgloss.Color {
	return lipgloss.Color("#cbe1e7")
}

// Bg returns the recommended default background color for this tint.
func (t *TintChallengerDeep) Bg() lipgloss.Color {
	return lipgloss.Color("#1e1c31")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintChallengerDeep) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintChallengerDeep) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintChallengerDeep) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#565575")
}

func (t *TintChallengerDeep) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#91ddff")
}

func (t *TintChallengerDeep) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#aaffe4")
}

func (t *TintChallengerDeep) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#95ffa4")
}

func (t *TintChallengerDeep) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#c991e1")
}

func (t *TintChallengerDeep) BrightRed() lipgloss.Color {
	return lipgloss.Color("#ff8080")
}

func (t *TintChallengerDeep) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#cbe3e7")
}

func (t *TintChallengerDeep) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffe9aa")
}

func (t *TintChallengerDeep) Black() lipgloss.Color {
	return lipgloss.Color("#141228")
}

func (t *TintChallengerDeep) Blue() lipgloss.Color {
	return lipgloss.Color("#65b2ff")
}

func (t *TintChallengerDeep) Cyan() lipgloss.Color {
	return lipgloss.Color("#63f2f1")
}

func (t *TintChallengerDeep) Green() lipgloss.Color {
	return lipgloss.Color("#62d196")
}

func (t *TintChallengerDeep) Purple() lipgloss.Color {
	return lipgloss.Color("#906cff")
}

func (t *TintChallengerDeep) Red() lipgloss.Color {
	return lipgloss.Color("#ff5458")
}

func (t *TintChallengerDeep) White() lipgloss.Color {
	return lipgloss.Color("#a6b3cc")
}

func (t *TintChallengerDeep) Yellow() lipgloss.Color {
	return lipgloss.Color("#ffb378")
}
