// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintCyberpunk (cyberpunk) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=cyberpunk
type TintCyberpunk struct{}

// DisplayName returns the display name of the tint.
func (t *TintCyberpunk) DisplayName() string {
	return "cyberpunk"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintCyberpunk) ID() string {
	return "cyberpunk"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintCyberpunk) About() string {
	return `Tint: cyberpunk`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintCyberpunk) Fg() lipgloss.Color {
	return lipgloss.Color("#e5e5e5")
}

// Bg returns the recommended default background color for this tint.
func (t *TintCyberpunk) Bg() lipgloss.Color {
	return lipgloss.Color("#332a57")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintCyberpunk) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintCyberpunk) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintCyberpunk) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintCyberpunk) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#1bccfd")
}

func (t *TintCyberpunk) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#99d6fc")
}

func (t *TintCyberpunk) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#21f6bc")
}

func (t *TintCyberpunk) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#e6aefe")
}

func (t *TintCyberpunk) BrightRed() lipgloss.Color {
	return lipgloss.Color("#ff8aa4")
}

func (t *TintCyberpunk) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintCyberpunk) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#fff787")
}

func (t *TintCyberpunk) Black() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintCyberpunk) Blue() lipgloss.Color {
	return lipgloss.Color("#00bfff")
}

func (t *TintCyberpunk) Cyan() lipgloss.Color {
	return lipgloss.Color("#86cbfe")
}

func (t *TintCyberpunk) Green() lipgloss.Color {
	return lipgloss.Color("#00fbac")
}

func (t *TintCyberpunk) Purple() lipgloss.Color {
	return lipgloss.Color("#df95ff")
}

func (t *TintCyberpunk) Red() lipgloss.Color {
	return lipgloss.Color("#ff7092")
}

func (t *TintCyberpunk) White() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintCyberpunk) Yellow() lipgloss.Color {
	return lipgloss.Color("#fffa6a")
}
