// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintCyberCube (Cyber Cube) is a collection of lipgloss styles.
type TintCyberCube struct{}

// DisplayName returns the display name of the tint.
func (t *TintCyberCube) DisplayName() string {
	return "Cyber Cube"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintCyberCube) ID() string {
	return "cyber_cube"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintCyberCube) About() string {
	return `Tint: Cyber Cube`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintCyberCube) Fg() lipgloss.Color {
	return lipgloss.Color("#A4B1CD")
}

// Bg returns the recommended default background color for this tint.
func (t *TintCyberCube) Bg() lipgloss.Color {
	return lipgloss.Color("#161C2B")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintCyberCube) SelectionBg() lipgloss.Color {
	return lipgloss.Color("#C5D1EB")
}

// Cursor returns the recommended color for the cursor.
func (t *TintCyberCube) Cursor() lipgloss.Color {
	return lipgloss.Color("#C5D1EB")
}

func (t *TintCyberCube) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#767676")
}

func (t *TintCyberCube) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#5CB2FF")
}

func (t *TintCyberCube) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#5CECC6")
}

func (t *TintCyberCube) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#C5F467")
}

func (t *TintCyberCube) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#CF8DFB")
}

func (t *TintCyberCube) BrightRed() lipgloss.Color {
	return lipgloss.Color("#FF8484")
}

func (t *TintCyberCube) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#D5DAFF")
}

func (t *TintCyberCube) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#FFCC5C")
}

func (t *TintCyberCube) Black() lipgloss.Color {
	return lipgloss.Color("#141D2B")
}

func (t *TintCyberCube) Blue() lipgloss.Color {
	return lipgloss.Color("#2E6CFF")
}

func (t *TintCyberCube) Cyan() lipgloss.Color {
	return lipgloss.Color("#2DE2B2")
}

func (t *TintCyberCube) Green() lipgloss.Color {
	return lipgloss.Color("#9FEF00")
}

func (t *TintCyberCube) Purple() lipgloss.Color {
	return lipgloss.Color("#9F00FF")
}

func (t *TintCyberCube) Red() lipgloss.Color {
	return lipgloss.Color("#FF3E3E")
}

func (t *TintCyberCube) White() lipgloss.Color {
	return lipgloss.Color("#D5E0FF")
}

func (t *TintCyberCube) Yellow() lipgloss.Color {
	return lipgloss.Color("#FFAF00")
}
