// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintENCOM (ENCOM) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=ENCOM
type TintENCOM struct{}

// DisplayName returns the display name of the tint.
func (t *TintENCOM) DisplayName() string {
	return "ENCOM"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintENCOM) ID() string {
	return "encom"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintENCOM) About() string {
	return `Tint: ENCOM`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintENCOM) Fg() lipgloss.Color {
	return lipgloss.Color("#00a595")
}

// Bg returns the recommended default background color for this tint.
func (t *TintENCOM) Bg() lipgloss.Color {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintENCOM) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintENCOM) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintENCOM) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#555555")
}

func (t *TintENCOM) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#0000ff")
}

func (t *TintENCOM) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#00cdcd")
}

func (t *TintENCOM) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#00ee00")
}

func (t *TintENCOM) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#ff00ff")
}

func (t *TintENCOM) BrightRed() lipgloss.Color {
	return lipgloss.Color("#ff0000")
}

func (t *TintENCOM) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintENCOM) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffff00")
}

func (t *TintENCOM) Black() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintENCOM) Blue() lipgloss.Color {
	return lipgloss.Color("#0081ff")
}

func (t *TintENCOM) Cyan() lipgloss.Color {
	return lipgloss.Color("#008b8b")
}

func (t *TintENCOM) Green() lipgloss.Color {
	return lipgloss.Color("#008b00")
}

func (t *TintENCOM) Purple() lipgloss.Color {
	return lipgloss.Color("#bc00ca")
}

func (t *TintENCOM) Red() lipgloss.Color {
	return lipgloss.Color("#9f0000")
}

func (t *TintENCOM) White() lipgloss.Color {
	return lipgloss.Color("#bbbbbb")
}

func (t *TintENCOM) Yellow() lipgloss.Color {
	return lipgloss.Color("#ffd000")
}
