// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintForestBlue (ForestBlue) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=ForestBlue
type TintForestBlue struct{}

// DisplayName returns the display name of the tint.
func (t *TintForestBlue) DisplayName() string {
	return "ForestBlue"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintForestBlue) ID() string {
	return "forest_blue"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintForestBlue) About() string {
	return `Tint: ForestBlue`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintForestBlue) Fg() lipgloss.Color {
	return lipgloss.Color("#e2d8cd")
}

// Bg returns the recommended default background color for this tint.
func (t *TintForestBlue) Bg() lipgloss.Color {
	return lipgloss.Color("#051519")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintForestBlue) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintForestBlue) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintForestBlue) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#3d3d3d")
}

func (t *TintForestBlue) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#39a7a2")
}

func (t *TintForestBlue) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#6096bf")
}

func (t *TintForestBlue) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#6bb48d")
}

func (t *TintForestBlue) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#7e62b3")
}

func (t *TintForestBlue) BrightRed() lipgloss.Color {
	return lipgloss.Color("#fb3d66")
}

func (t *TintForestBlue) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#e2d8cd")
}

func (t *TintForestBlue) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#30c85a")
}

func (t *TintForestBlue) Black() lipgloss.Color {
	return lipgloss.Color("#333333")
}

func (t *TintForestBlue) Blue() lipgloss.Color {
	return lipgloss.Color("#8ed0ce")
}

func (t *TintForestBlue) Cyan() lipgloss.Color {
	return lipgloss.Color("#31658c")
}

func (t *TintForestBlue) Green() lipgloss.Color {
	return lipgloss.Color("#92d3a2")
}

func (t *TintForestBlue) Purple() lipgloss.Color {
	return lipgloss.Color("#5e468c")
}

func (t *TintForestBlue) Red() lipgloss.Color {
	return lipgloss.Color("#f8818e")
}

func (t *TintForestBlue) White() lipgloss.Color {
	return lipgloss.Color("#e2d8cd")
}

func (t *TintForestBlue) Yellow() lipgloss.Color {
	return lipgloss.Color("#1a8e63")
}
