// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintGlacier (Glacier) is a collection of lipgloss styles.
type TintGlacier struct{}

// DisplayName returns the display name of the tint.
func (t *TintGlacier) DisplayName() string {
	return "Glacier"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintGlacier) ID() string {
	return "glacier"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintGlacier) About() string {
	return `Tint: Glacier`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintGlacier) Fg() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintGlacier) Bg() lipgloss.Color {
	return lipgloss.Color("#0c1115")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintGlacier) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintGlacier) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintGlacier) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#404a55")
}

func (t *TintGlacier) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#2a8bc1")
}

func (t *TintGlacier) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#a0b6d3")
}

func (t *TintGlacier) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#49e998")
}

func (t *TintGlacier) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#ea4727")
}

func (t *TintGlacier) BrightRed() lipgloss.Color {
	return lipgloss.Color("#bd0f2f")
}

func (t *TintGlacier) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintGlacier) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#fddf6e")
}

func (t *TintGlacier) Black() lipgloss.Color {
	return lipgloss.Color("#2e343c")
}

func (t *TintGlacier) Blue() lipgloss.Color {
	return lipgloss.Color("#1f5872")
}

func (t *TintGlacier) Cyan() lipgloss.Color {
	return lipgloss.Color("#778397")
}

func (t *TintGlacier) Green() lipgloss.Color {
	return lipgloss.Color("#35a770")
}

func (t *TintGlacier) Purple() lipgloss.Color {
	return lipgloss.Color("#bd2523")
}

func (t *TintGlacier) Red() lipgloss.Color {
	return lipgloss.Color("#bd0f2f")
}

func (t *TintGlacier) White() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintGlacier) Yellow() lipgloss.Color {
	return lipgloss.Color("#fb9435")
}
