// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintGrass (Grass) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Grass
type TintGrass struct{}

// DisplayName returns the display name of the tint.
func (t *TintGrass) DisplayName() string {
	return "Grass"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintGrass) ID() string {
	return "grass"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintGrass) About() string {
	return `Tint: Grass`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintGrass) Fg() lipgloss.Color {
	return lipgloss.Color("#fff0a5")
}

// Bg returns the recommended default background color for this tint.
func (t *TintGrass) Bg() lipgloss.Color {
	return lipgloss.Color("#13773d")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintGrass) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintGrass) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintGrass) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#555555")
}

func (t *TintGrass) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#0000bb")
}

func (t *TintGrass) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#55ffff")
}

func (t *TintGrass) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#00bb00")
}

func (t *TintGrass) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#ff55ff")
}

func (t *TintGrass) BrightRed() lipgloss.Color {
	return lipgloss.Color("#bb0000")
}

func (t *TintGrass) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintGrass) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#e7b000")
}

func (t *TintGrass) Black() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintGrass) Blue() lipgloss.Color {
	return lipgloss.Color("#0000a3")
}

func (t *TintGrass) Cyan() lipgloss.Color {
	return lipgloss.Color("#00bbbb")
}

func (t *TintGrass) Green() lipgloss.Color {
	return lipgloss.Color("#00bb00")
}

func (t *TintGrass) Purple() lipgloss.Color {
	return lipgloss.Color("#950062")
}

func (t *TintGrass) Red() lipgloss.Color {
	return lipgloss.Color("#bb0000")
}

func (t *TintGrass) White() lipgloss.Color {
	return lipgloss.Color("#bbbbbb")
}

func (t *TintGrass) Yellow() lipgloss.Color {
	return lipgloss.Color("#e7b000")
}
