// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintH4RithdCom (h4rithd.com) is a collection of lipgloss styles.
type TintH4RithdCom struct{}

// DisplayName returns the display name of the tint.
func (t *TintH4RithdCom) DisplayName() string {
	return "h4rithd.com"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintH4RithdCom) ID() string {
	return "h_4_rithd_com"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintH4RithdCom) About() string {
	return `Tint: h4rithd.com`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintH4RithdCom) Fg() lipgloss.Color {
	return lipgloss.Color("#FFFEFF")
}

// Bg returns the recommended default background color for this tint.
func (t *TintH4RithdCom) Bg() lipgloss.Color {
	return lipgloss.Color("#1E1E1E")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintH4RithdCom) SelectionBg() lipgloss.Color {
	return lipgloss.Color("#FFFFFF")
}

// Cursor returns the recommended color for the cursor.
func (t *TintH4RithdCom) Cursor() lipgloss.Color {
	return lipgloss.Color("#FFFFFF")
}

func (t *TintH4RithdCom) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#545752")
}

func (t *TintH4RithdCom) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#729ECE")
}

func (t *TintH4RithdCom) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#35E2E3")
}

func (t *TintH4RithdCom) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#8BE235")
}

func (t *TintH4RithdCom) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#AC7EA8")
}

func (t *TintH4RithdCom) BrightRed() lipgloss.Color {
	return lipgloss.Color("#EE282B")
}

func (t *TintH4RithdCom) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#D3D7CF")
}

func (t *TintH4RithdCom) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#FDE94E")
}

func (t *TintH4RithdCom) Black() lipgloss.Color {
	return lipgloss.Color("#010100")
}

func (t *TintH4RithdCom) Blue() lipgloss.Color {
	return lipgloss.Color("#3464A5")
}

func (t *TintH4RithdCom) Cyan() lipgloss.Color {
	return lipgloss.Color("#06989A")
}

func (t *TintH4RithdCom) Green() lipgloss.Color {
	return lipgloss.Color("#4E9B07")
}

func (t *TintH4RithdCom) Purple() lipgloss.Color {
	return lipgloss.Color("#75517A")
}

func (t *TintH4RithdCom) Red() lipgloss.Color {
	return lipgloss.Color("#CC0000")
}

func (t *TintH4RithdCom) White() lipgloss.Color {
	return lipgloss.Color("#D3D7CF")
}

func (t *TintH4RithdCom) Yellow() lipgloss.Color {
	return lipgloss.Color("#C4A000")
}
