// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintJetBrainsDarcula (JetBrains Darcula) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=JetBrains+Darcula
type TintJetBrainsDarcula struct{}

// DisplayName returns the display name of the tint.
func (t *TintJetBrainsDarcula) DisplayName() string {
	return "JetBrains Darcula"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintJetBrainsDarcula) ID() string {
	return "jet_brains_darcula"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintJetBrainsDarcula) About() string {
	return `Tint: JetBrains Darcula`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintJetBrainsDarcula) Fg() lipgloss.Color {
	return lipgloss.Color("#adadad")
}

// Bg returns the recommended default background color for this tint.
func (t *TintJetBrainsDarcula) Bg() lipgloss.Color {
	return lipgloss.Color("#202020")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintJetBrainsDarcula) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintJetBrainsDarcula) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintJetBrainsDarcula) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#555555")
}

func (t *TintJetBrainsDarcula) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#6d9df1")
}

func (t *TintJetBrainsDarcula) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#60d3d1")
}

func (t *TintJetBrainsDarcula) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#67ff4f")
}

func (t *TintJetBrainsDarcula) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#fb82ff")
}

func (t *TintJetBrainsDarcula) BrightRed() lipgloss.Color {
	return lipgloss.Color("#fb7172")
}

func (t *TintJetBrainsDarcula) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#eeeeee")
}

func (t *TintJetBrainsDarcula) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffff00")
}

func (t *TintJetBrainsDarcula) Black() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintJetBrainsDarcula) Blue() lipgloss.Color {
	return lipgloss.Color("#4581eb")
}

func (t *TintJetBrainsDarcula) Cyan() lipgloss.Color {
	return lipgloss.Color("#33c2c1")
}

func (t *TintJetBrainsDarcula) Green() lipgloss.Color {
	return lipgloss.Color("#126e00")
}

func (t *TintJetBrainsDarcula) Purple() lipgloss.Color {
	return lipgloss.Color("#fa54ff")
}

func (t *TintJetBrainsDarcula) Red() lipgloss.Color {
	return lipgloss.Color("#fa5355")
}

func (t *TintJetBrainsDarcula) White() lipgloss.Color {
	return lipgloss.Color("#adadad")
}

func (t *TintJetBrainsDarcula) Yellow() lipgloss.Color {
	return lipgloss.Color("#c2c300")
}
