// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintLiquidCarbonTransparentInverse (LiquidCarbonTransparentInverse) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=LiquidCarbonTransparentInverse
type TintLiquidCarbonTransparentInverse struct{}

// DisplayName returns the display name of the tint.
func (t *TintLiquidCarbonTransparentInverse) DisplayName() string {
	return "LiquidCarbonTransparentInverse"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintLiquidCarbonTransparentInverse) ID() string {
	return "liquid_carbon_transparent_inverse"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintLiquidCarbonTransparentInverse) About() string {
	return `Tint: LiquidCarbonTransparentInverse`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintLiquidCarbonTransparentInverse) Fg() lipgloss.Color {
	return lipgloss.Color("#afc2c2")
}

// Bg returns the recommended default background color for this tint.
func (t *TintLiquidCarbonTransparentInverse) Bg() lipgloss.Color {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintLiquidCarbonTransparentInverse) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintLiquidCarbonTransparentInverse) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintLiquidCarbonTransparentInverse) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintLiquidCarbonTransparentInverse) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#0099cc")
}

func (t *TintLiquidCarbonTransparentInverse) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#7ac4cc")
}

func (t *TintLiquidCarbonTransparentInverse) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#559a70")
}

func (t *TintLiquidCarbonTransparentInverse) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#cc69c8")
}

func (t *TintLiquidCarbonTransparentInverse) BrightRed() lipgloss.Color {
	return lipgloss.Color("#ff3030")
}

func (t *TintLiquidCarbonTransparentInverse) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintLiquidCarbonTransparentInverse) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ccac00")
}

func (t *TintLiquidCarbonTransparentInverse) Black() lipgloss.Color {
	return lipgloss.Color("#bccccd")
}

func (t *TintLiquidCarbonTransparentInverse) Blue() lipgloss.Color {
	return lipgloss.Color("#0099cc")
}

func (t *TintLiquidCarbonTransparentInverse) Cyan() lipgloss.Color {
	return lipgloss.Color("#7ac4cc")
}

func (t *TintLiquidCarbonTransparentInverse) Green() lipgloss.Color {
	return lipgloss.Color("#559a70")
}

func (t *TintLiquidCarbonTransparentInverse) Purple() lipgloss.Color {
	return lipgloss.Color("#cc69c8")
}

func (t *TintLiquidCarbonTransparentInverse) Red() lipgloss.Color {
	return lipgloss.Color("#ff3030")
}

func (t *TintLiquidCarbonTransparentInverse) White() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintLiquidCarbonTransparentInverse) Yellow() lipgloss.Color {
	return lipgloss.Color("#ccac00")
}
