// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintMaterialOcean (MaterialOcean) is a collection of lipgloss styles.
type TintMaterialOcean struct{}

// DisplayName returns the display name of the tint.
func (t *TintMaterialOcean) DisplayName() string {
	return "MaterialOcean"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintMaterialOcean) ID() string {
	return "material_ocean"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintMaterialOcean) About() string {
	return `Tint: MaterialOcean`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintMaterialOcean) Fg() lipgloss.Color {
	return lipgloss.Color("#8f93a2")
}

// Bg returns the recommended default background color for this tint.
func (t *TintMaterialOcean) Bg() lipgloss.Color {
	return lipgloss.Color("#0f111a")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintMaterialOcean) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintMaterialOcean) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintMaterialOcean) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#546e7a")
}

func (t *TintMaterialOcean) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#82aaff")
}

func (t *TintMaterialOcean) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#89ddff")
}

func (t *TintMaterialOcean) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#c3e88d")
}

func (t *TintMaterialOcean) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#c792ea")
}

func (t *TintMaterialOcean) BrightRed() lipgloss.Color {
	return lipgloss.Color("#ff5370")
}

func (t *TintMaterialOcean) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintMaterialOcean) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffcb6b")
}

func (t *TintMaterialOcean) Black() lipgloss.Color {
	return lipgloss.Color("#546e7a")
}

func (t *TintMaterialOcean) Blue() lipgloss.Color {
	return lipgloss.Color("#82aaff")
}

func (t *TintMaterialOcean) Cyan() lipgloss.Color {
	return lipgloss.Color("#89ddff")
}

func (t *TintMaterialOcean) Green() lipgloss.Color {
	return lipgloss.Color("#c3e88d")
}

func (t *TintMaterialOcean) Purple() lipgloss.Color {
	return lipgloss.Color("#c792ea")
}

func (t *TintMaterialOcean) Red() lipgloss.Color {
	return lipgloss.Color("#ff5370")
}

func (t *TintMaterialOcean) White() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintMaterialOcean) Yellow() lipgloss.Color {
	return lipgloss.Color("#ffcb6b")
}
