// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintMonokaiOctagon (Monokai Octagon) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Monokai+Octagon
type TintMonokaiOctagon struct{}

// DisplayName returns the display name of the tint.
func (t *TintMonokaiOctagon) DisplayName() string {
	return "Monokai Octagon"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintMonokaiOctagon) ID() string {
	return "monokai_octagon"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintMonokaiOctagon) About() string {
	return `Tint: Monokai Octagon`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintMonokaiOctagon) Fg() lipgloss.Color {
	return lipgloss.Color("#eaf2f1")
}

// Bg returns the recommended default background color for this tint.
func (t *TintMonokaiOctagon) Bg() lipgloss.Color {
	return lipgloss.Color("#282a3a")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintMonokaiOctagon) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintMonokaiOctagon) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintMonokaiOctagon) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#686a66")
}

func (t *TintMonokaiOctagon) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#84b0d8")
}

func (t *TintMonokaiOctagon) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#37e6e8")
}

func (t *TintMonokaiOctagon) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#99e343")
}

func (t *TintMonokaiOctagon) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#bc94b7")
}

func (t *TintMonokaiOctagon) BrightRed() lipgloss.Color {
	return lipgloss.Color("#f54235")
}

func (t *TintMonokaiOctagon) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#f1f1f0")
}

func (t *TintMonokaiOctagon) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#fdeb61")
}

func (t *TintMonokaiOctagon) Black() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintMonokaiOctagon) Blue() lipgloss.Color {
	return lipgloss.Color("#427ab3")
}

func (t *TintMonokaiOctagon) Cyan() lipgloss.Color {
	return lipgloss.Color("#00a7aa")
}

func (t *TintMonokaiOctagon) Green() lipgloss.Color {
	return lipgloss.Color("#5ea702")
}

func (t *TintMonokaiOctagon) Purple() lipgloss.Color {
	return lipgloss.Color("#89658e")
}

func (t *TintMonokaiOctagon) Red() lipgloss.Color {
	return lipgloss.Color("#d81e00")
}

func (t *TintMonokaiOctagon) White() lipgloss.Color {
	return lipgloss.Color("#dbded8")
}

func (t *TintMonokaiOctagon) Yellow() lipgloss.Color {
	return lipgloss.Color("#cfae00")
}
