// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintNightOwlishLight (Night Owlish Light) is a collection of lipgloss styles.
type TintNightOwlishLight struct{}

// DisplayName returns the display name of the tint.
func (t *TintNightOwlishLight) DisplayName() string {
	return "Night Owlish Light"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintNightOwlishLight) ID() string {
	return "night_owlish_light"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintNightOwlishLight) About() string {
	return `Tint: Night Owlish Light`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintNightOwlishLight) Fg() lipgloss.Color {
	return lipgloss.Color("#403f53")
}

// Bg returns the recommended default background color for this tint.
func (t *TintNightOwlishLight) Bg() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintNightOwlishLight) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintNightOwlishLight) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintNightOwlishLight) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#7a8181")
}

func (t *TintNightOwlishLight) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#5ca7e4")
}

func (t *TintNightOwlishLight) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#00c990")
}

func (t *TintNightOwlishLight) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#49d0c5")
}

func (t *TintNightOwlishLight) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#697098")
}

func (t *TintNightOwlishLight) BrightRed() lipgloss.Color {
	return lipgloss.Color("#f76e6e")
}

func (t *TintNightOwlishLight) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#989fb1")
}

func (t *TintNightOwlishLight) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#dac26b")
}

func (t *TintNightOwlishLight) Black() lipgloss.Color {
	return lipgloss.Color("#011627")
}

func (t *TintNightOwlishLight) Blue() lipgloss.Color {
	return lipgloss.Color("#4876d6")
}

func (t *TintNightOwlishLight) Cyan() lipgloss.Color {
	return lipgloss.Color("#08916a")
}

func (t *TintNightOwlishLight) Green() lipgloss.Color {
	return lipgloss.Color("#2aa298")
}

func (t *TintNightOwlishLight) Purple() lipgloss.Color {
	return lipgloss.Color("#403f53")
}

func (t *TintNightOwlishLight) Red() lipgloss.Color {
	return lipgloss.Color("#d3423e")
}

func (t *TintNightOwlishLight) White() lipgloss.Color {
	return lipgloss.Color("#7a8181")
}

func (t *TintNightOwlishLight) Yellow() lipgloss.Color {
	return lipgloss.Color("#daaa01")
}
