// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintNord (nord) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=nord
type TintNord struct{}

// DisplayName returns the display name of the tint.
func (t *TintNord) DisplayName() string {
	return "nord"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintNord) ID() string {
	return "nord"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintNord) About() string {
	return `Tint: nord`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintNord) Fg() lipgloss.Color {
	return lipgloss.Color("#d8dee9")
}

// Bg returns the recommended default background color for this tint.
func (t *TintNord) Bg() lipgloss.Color {
	return lipgloss.Color("#2e3440")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintNord) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintNord) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintNord) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#4c566a")
}

func (t *TintNord) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#81a1c1")
}

func (t *TintNord) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#8fbcbb")
}

func (t *TintNord) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#a3be8c")
}

func (t *TintNord) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#b48ead")
}

func (t *TintNord) BrightRed() lipgloss.Color {
	return lipgloss.Color("#bf616a")
}

func (t *TintNord) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#eceff4")
}

func (t *TintNord) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ebcb8b")
}

func (t *TintNord) Black() lipgloss.Color {
	return lipgloss.Color("#3b4252")
}

func (t *TintNord) Blue() lipgloss.Color {
	return lipgloss.Color("#81a1c1")
}

func (t *TintNord) Cyan() lipgloss.Color {
	return lipgloss.Color("#88c0d0")
}

func (t *TintNord) Green() lipgloss.Color {
	return lipgloss.Color("#a3be8c")
}

func (t *TintNord) Purple() lipgloss.Color {
	return lipgloss.Color("#b48ead")
}

func (t *TintNord) Red() lipgloss.Color {
	return lipgloss.Color("#bf616a")
}

func (t *TintNord) White() lipgloss.Color {
	return lipgloss.Color("#e5e9f0")
}

func (t *TintNord) Yellow() lipgloss.Color {
	return lipgloss.Color("#ebcb8b")
}
