// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintRebecca (rebecca) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=rebecca
type TintRebecca struct{}

// DisplayName returns the display name of the tint.
func (t *TintRebecca) DisplayName() string {
	return "rebecca"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintRebecca) ID() string {
	return "rebecca"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintRebecca) About() string {
	return `Tint: rebecca`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintRebecca) Fg() lipgloss.Color {
	return lipgloss.Color("#e8e6ed")
}

// Bg returns the recommended default background color for this tint.
func (t *TintRebecca) Bg() lipgloss.Color {
	return lipgloss.Color("#292a44")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintRebecca) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintRebecca) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintRebecca) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#666699")
}

func (t *TintRebecca) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#69c0fa")
}

func (t *TintRebecca) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#8bfde1")
}

func (t *TintRebecca) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#01eac0")
}

func (t *TintRebecca) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#c17ff8")
}

func (t *TintRebecca) BrightRed() lipgloss.Color {
	return lipgloss.Color("#ff92cd")
}

func (t *TintRebecca) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#f4f2f9")
}

func (t *TintRebecca) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#fffca8")
}

func (t *TintRebecca) Black() lipgloss.Color {
	return lipgloss.Color("#12131e")
}

func (t *TintRebecca) Blue() lipgloss.Color {
	return lipgloss.Color("#7aa5ff")
}

func (t *TintRebecca) Cyan() lipgloss.Color {
	return lipgloss.Color("#56d3c2")
}

func (t *TintRebecca) Green() lipgloss.Color {
	return lipgloss.Color("#04dbb5")
}

func (t *TintRebecca) Purple() lipgloss.Color {
	return lipgloss.Color("#bf9cf9")
}

func (t *TintRebecca) Red() lipgloss.Color {
	return lipgloss.Color("#dd7755")
}

func (t *TintRebecca) White() lipgloss.Color {
	return lipgloss.Color("#e4e3e9")
}

func (t *TintRebecca) Yellow() lipgloss.Color {
	return lipgloss.Color("#f2e7b7")
}
