// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintRippedcasts (Rippedcasts) is a collection of lipgloss styles.
type TintRippedcasts struct{}

// DisplayName returns the display name of the tint.
func (t *TintRippedcasts) DisplayName() string {
	return "Rippedcasts"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintRippedcasts) ID() string {
	return "rippedcasts"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintRippedcasts) About() string {
	return `Tint: Rippedcasts`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintRippedcasts) Fg() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintRippedcasts) Bg() lipgloss.Color {
	return lipgloss.Color("#2b2b2b")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintRippedcasts) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintRippedcasts) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintRippedcasts) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#666666")
}

func (t *TintRippedcasts) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#86bdc9")
}

func (t *TintRippedcasts) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#8c9bc4")
}

func (t *TintRippedcasts) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#bcee68")
}

func (t *TintRippedcasts) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#e500e5")
}

func (t *TintRippedcasts) BrightRed() lipgloss.Color {
	return lipgloss.Color("#eecbad")
}

func (t *TintRippedcasts) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#e5e5e5")
}

func (t *TintRippedcasts) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#e5e500")
}

func (t *TintRippedcasts) Black() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintRippedcasts) Blue() lipgloss.Color {
	return lipgloss.Color("#75a5b0")
}

func (t *TintRippedcasts) Cyan() lipgloss.Color {
	return lipgloss.Color("#5a647e")
}

func (t *TintRippedcasts) Green() lipgloss.Color {
	return lipgloss.Color("#a8ff60")
}

func (t *TintRippedcasts) Purple() lipgloss.Color {
	return lipgloss.Color("#ff73fd")
}

func (t *TintRippedcasts) Red() lipgloss.Color {
	return lipgloss.Color("#cdaf95")
}

func (t *TintRippedcasts) White() lipgloss.Color {
	return lipgloss.Color("#bfbfbf")
}

func (t *TintRippedcasts) Yellow() lipgloss.Color {
	return lipgloss.Color("#bfbb1f")
}
