// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintSakura (Sakura) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Sakura
type TintSakura struct{}

// DisplayName returns the display name of the tint.
func (t *TintSakura) DisplayName() string {
	return "Sakura"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintSakura) ID() string {
	return "sakura"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintSakura) About() string {
	return `Tint: Sakura`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintSakura) Fg() lipgloss.Color {
	return lipgloss.Color("#dd7bdc")
}

// Bg returns the recommended default background color for this tint.
func (t *TintSakura) Bg() lipgloss.Color {
	return lipgloss.Color("#18131e")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintSakura) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintSakura) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintSakura) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#786d69")
}

func (t *TintSakura) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#9892f1")
}

func (t *TintSakura) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#eeeeee")
}

func (t *TintSakura) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#22e529")
}

func (t *TintSakura) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#e90cdd")
}

func (t *TintSakura) BrightRed() lipgloss.Color {
	return lipgloss.Color("#f41d99")
}

func (t *TintSakura) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#cbb6ff")
}

func (t *TintSakura) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#f59574")
}

func (t *TintSakura) Black() lipgloss.Color {
	return lipgloss.Color("#000000")
}

func (t *TintSakura) Blue() lipgloss.Color {
	return lipgloss.Color("#6964ab")
}

func (t *TintSakura) Cyan() lipgloss.Color {
	return lipgloss.Color("#939393")
}

func (t *TintSakura) Green() lipgloss.Color {
	return lipgloss.Color("#41af1a")
}

func (t *TintSakura) Purple() lipgloss.Color {
	return lipgloss.Color("#c71fbf")
}

func (t *TintSakura) Red() lipgloss.Color {
	return lipgloss.Color("#d52370")
}

func (t *TintSakura) White() lipgloss.Color {
	return lipgloss.Color("#998eac")
}

func (t *TintSakura) Yellow() lipgloss.Color {
	return lipgloss.Color("#bc7053")
}
