// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintSeafoamPastel (Seafoam Pastel) is a collection of lipgloss styles.
type TintSeafoamPastel struct{}

// DisplayName returns the display name of the tint.
func (t *TintSeafoamPastel) DisplayName() string {
	return "Seafoam Pastel"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintSeafoamPastel) ID() string {
	return "seafoam_pastel"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintSeafoamPastel) About() string {
	return `Tint: Seafoam Pastel`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintSeafoamPastel) Fg() lipgloss.Color {
	return lipgloss.Color("#d4e7d4")
}

// Bg returns the recommended default background color for this tint.
func (t *TintSeafoamPastel) Bg() lipgloss.Color {
	return lipgloss.Color("#243435")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintSeafoamPastel) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintSeafoamPastel) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintSeafoamPastel) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#8a8a8a")
}

func (t *TintSeafoamPastel) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#7ac3cf")
}

func (t *TintSeafoamPastel) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#ade0e0")
}

func (t *TintSeafoamPastel) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#98d9aa")
}

func (t *TintSeafoamPastel) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#d6b2a1")
}

func (t *TintSeafoamPastel) BrightRed() lipgloss.Color {
	return lipgloss.Color("#cf937a")
}

func (t *TintSeafoamPastel) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#e0e0e0")
}

func (t *TintSeafoamPastel) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#fae79d")
}

func (t *TintSeafoamPastel) Black() lipgloss.Color {
	return lipgloss.Color("#757575")
}

func (t *TintSeafoamPastel) Blue() lipgloss.Color {
	return lipgloss.Color("#4d7b82")
}

func (t *TintSeafoamPastel) Cyan() lipgloss.Color {
	return lipgloss.Color("#729494")
}

func (t *TintSeafoamPastel) Green() lipgloss.Color {
	return lipgloss.Color("#728c62")
}

func (t *TintSeafoamPastel) Purple() lipgloss.Color {
	return lipgloss.Color("#8a7267")
}

func (t *TintSeafoamPastel) Red() lipgloss.Color {
	return lipgloss.Color("#825d4d")
}

func (t *TintSeafoamPastel) White() lipgloss.Color {
	return lipgloss.Color("#e0e0e0")
}

func (t *TintSeafoamPastel) Yellow() lipgloss.Color {
	return lipgloss.Color("#ada16d")
}
