// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintSeti (Seti) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Seti
type TintSeti struct{}

// DisplayName returns the display name of the tint.
func (t *TintSeti) DisplayName() string {
	return "Seti"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintSeti) ID() string {
	return "seti"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintSeti) About() string {
	return `Tint: Seti`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintSeti) Fg() lipgloss.Color {
	return lipgloss.Color("#cacecd")
}

// Bg returns the recommended default background color for this tint.
func (t *TintSeti) Bg() lipgloss.Color {
	return lipgloss.Color("#111213")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintSeti) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintSeti) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintSeti) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#323232")
}

func (t *TintSeti) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#43a5d5")
}

func (t *TintSeti) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#8ec43d")
}

func (t *TintSeti) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#8ec43d")
}

func (t *TintSeti) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#8b57b5")
}

func (t *TintSeti) BrightRed() lipgloss.Color {
	return lipgloss.Color("#c22832")
}

func (t *TintSeti) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

func (t *TintSeti) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#e0c64f")
}

func (t *TintSeti) Black() lipgloss.Color {
	return lipgloss.Color("#323232")
}

func (t *TintSeti) Blue() lipgloss.Color {
	return lipgloss.Color("#43a5d5")
}

func (t *TintSeti) Cyan() lipgloss.Color {
	return lipgloss.Color("#8ec43d")
}

func (t *TintSeti) Green() lipgloss.Color {
	return lipgloss.Color("#8ec43d")
}

func (t *TintSeti) Purple() lipgloss.Color {
	return lipgloss.Color("#8b57b5")
}

func (t *TintSeti) Red() lipgloss.Color {
	return lipgloss.Color("#c22832")
}

func (t *TintSeti) White() lipgloss.Color {
	return lipgloss.Color("#eeeeee")
}

func (t *TintSeti) Yellow() lipgloss.Color {
	return lipgloss.Color("#e0c64f")
}
