// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintTomorrowNightBurns (Tomorrow Night Burns) is a collection of lipgloss styles.
type TintTomorrowNightBurns struct{}

// DisplayName returns the display name of the tint.
func (t *TintTomorrowNightBurns) DisplayName() string {
	return "Tomorrow Night Burns"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintTomorrowNightBurns) ID() string {
	return "tomorrow_night_burns"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintTomorrowNightBurns) About() string {
	return `Tint: Tomorrow Night Burns`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintTomorrowNightBurns) Fg() lipgloss.Color {
	return lipgloss.Color("#a1b0b8")
}

// Bg returns the recommended default background color for this tint.
func (t *TintTomorrowNightBurns) Bg() lipgloss.Color {
	return lipgloss.Color("#151515")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintTomorrowNightBurns) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintTomorrowNightBurns) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintTomorrowNightBurns) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#5d6f71")
}

func (t *TintTomorrowNightBurns) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#fc595f")
}

func (t *TintTomorrowNightBurns) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#ba8586")
}

func (t *TintTomorrowNightBurns) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#a63c40")
}

func (t *TintTomorrowNightBurns) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#df9395")
}

func (t *TintTomorrowNightBurns) BrightRed() lipgloss.Color {
	return lipgloss.Color("#832e31")
}

func (t *TintTomorrowNightBurns) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#f5f5f5")
}

func (t *TintTomorrowNightBurns) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#d2494e")
}

func (t *TintTomorrowNightBurns) Black() lipgloss.Color {
	return lipgloss.Color("#252525")
}

func (t *TintTomorrowNightBurns) Blue() lipgloss.Color {
	return lipgloss.Color("#fc595f")
}

func (t *TintTomorrowNightBurns) Cyan() lipgloss.Color {
	return lipgloss.Color("#ba8586")
}

func (t *TintTomorrowNightBurns) Green() lipgloss.Color {
	return lipgloss.Color("#a63c40")
}

func (t *TintTomorrowNightBurns) Purple() lipgloss.Color {
	return lipgloss.Color("#df9395")
}

func (t *TintTomorrowNightBurns) Red() lipgloss.Color {
	return lipgloss.Color("#832e31")
}

func (t *TintTomorrowNightBurns) White() lipgloss.Color {
	return lipgloss.Color("#f5f5f5")
}

func (t *TintTomorrowNightBurns) Yellow() lipgloss.Color {
	return lipgloss.Color("#d3494e")
}
