// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintTomorrowNightBright (Tomorrow Night Bright) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Tomorrow+Night+Bright
type TintTomorrowNightBright struct{}

// DisplayName returns the display name of the tint.
func (t *TintTomorrowNightBright) DisplayName() string {
	return "Tomorrow Night Bright"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintTomorrowNightBright) ID() string {
	return "tomorrow_night_bright"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintTomorrowNightBright) About() string {
	return `Tint: Tomorrow Night Bright`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintTomorrowNightBright) Fg() lipgloss.TerminalColor {
	return lipgloss.Color("#eaeaea")
}

// Bg returns the recommended default background color for this tint.
func (t *TintTomorrowNightBright) Bg() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintTomorrowNightBright) SelectionBg() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

// Cursor returns the recommended color for the cursor.
func (t *TintTomorrowNightBright) Cursor() lipgloss.TerminalColor {
	return lipgloss.NoColor{}
}

func (t *TintTomorrowNightBright) BrightBlack() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintTomorrowNightBright) BrightBlue() lipgloss.TerminalColor {
	return lipgloss.Color("#7aa6da")
}

func (t *TintTomorrowNightBright) BrightCyan() lipgloss.TerminalColor {
	return lipgloss.Color("#70c0b1")
}

func (t *TintTomorrowNightBright) BrightGreen() lipgloss.TerminalColor {
	return lipgloss.Color("#b9ca4a")
}

func (t *TintTomorrowNightBright) BrightPurple() lipgloss.TerminalColor {
	return lipgloss.Color("#c397d8")
}

func (t *TintTomorrowNightBright) BrightRed() lipgloss.TerminalColor {
	return lipgloss.Color("#d54e53")
}

func (t *TintTomorrowNightBright) BrightWhite() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintTomorrowNightBright) BrightYellow() lipgloss.TerminalColor {
	return lipgloss.Color("#e7c547")
}

func (t *TintTomorrowNightBright) Black() lipgloss.TerminalColor {
	return lipgloss.Color("#000000")
}

func (t *TintTomorrowNightBright) Blue() lipgloss.TerminalColor {
	return lipgloss.Color("#7aa6da")
}

func (t *TintTomorrowNightBright) Cyan() lipgloss.TerminalColor {
	return lipgloss.Color("#70c0b1")
}

func (t *TintTomorrowNightBright) Green() lipgloss.TerminalColor {
	return lipgloss.Color("#b9ca4a")
}

func (t *TintTomorrowNightBright) Purple() lipgloss.TerminalColor {
	return lipgloss.Color("#c397d8")
}

func (t *TintTomorrowNightBright) Red() lipgloss.TerminalColor {
	return lipgloss.Color("#d54e53")
}

func (t *TintTomorrowNightBright) White() lipgloss.TerminalColor {
	return lipgloss.Color("#ffffff")
}

func (t *TintTomorrowNightBright) Yellow() lipgloss.TerminalColor {
	return lipgloss.Color("#e7c547")
}
