// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintToyChest (ToyChest) is a collection of lipgloss styles.
type TintToyChest struct{}

// DisplayName returns the display name of the tint.
func (t *TintToyChest) DisplayName() string {
	return "ToyChest"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintToyChest) ID() string {
	return "toy_chest"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintToyChest) About() string {
	return `Tint: ToyChest`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintToyChest) Fg() lipgloss.Color {
	return lipgloss.Color("#31d07b")
}

// Bg returns the recommended default background color for this tint.
func (t *TintToyChest) Bg() lipgloss.Color {
	return lipgloss.Color("#24364b")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintToyChest) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintToyChest) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintToyChest) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#336889")
}

func (t *TintToyChest) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#34a6da")
}

func (t *TintToyChest) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#42c3ae")
}

func (t *TintToyChest) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#31d07b")
}

func (t *TintToyChest) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#ae6bdc")
}

func (t *TintToyChest) BrightRed() lipgloss.Color {
	return lipgloss.Color("#dd5944")
}

func (t *TintToyChest) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#d5d5d5")
}

func (t *TintToyChest) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#e7d84b")
}

func (t *TintToyChest) Black() lipgloss.Color {
	return lipgloss.Color("#2c3f58")
}

func (t *TintToyChest) Blue() lipgloss.Color {
	return lipgloss.Color("#325d96")
}

func (t *TintToyChest) Cyan() lipgloss.Color {
	return lipgloss.Color("#35a08f")
}

func (t *TintToyChest) Green() lipgloss.Color {
	return lipgloss.Color("#1a9172")
}

func (t *TintToyChest) Purple() lipgloss.Color {
	return lipgloss.Color("#8a5edc")
}

func (t *TintToyChest) Red() lipgloss.Color {
	return lipgloss.Color("#be2d26")
}

func (t *TintToyChest) White() lipgloss.Color {
	return lipgloss.Color("#23d183")
}

func (t *TintToyChest) Yellow() lipgloss.Color {
	return lipgloss.Color("#db8e27")
}
