// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintTwilight (Twilight) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=Twilight
type TintTwilight struct{}

// DisplayName returns the display name of the tint.
func (t *TintTwilight) DisplayName() string {
	return "Twilight"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintTwilight) ID() string {
	return "twilight"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintTwilight) About() string {
	return `Tint: Twilight`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintTwilight) Fg() lipgloss.Color {
	return lipgloss.Color("#ffffd4")
}

// Bg returns the recommended default background color for this tint.
func (t *TintTwilight) Bg() lipgloss.Color {
	return lipgloss.Color("#141414")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintTwilight) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintTwilight) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintTwilight) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#262626")
}

func (t *TintTwilight) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#5a5e62")
}

func (t *TintTwilight) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#8a989b")
}

func (t *TintTwilight) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#ccd88c")
}

func (t *TintTwilight) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#d0dc8e")
}

func (t *TintTwilight) BrightRed() lipgloss.Color {
	return lipgloss.Color("#de7c4c")
}

func (t *TintTwilight) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#ffffd4")
}

func (t *TintTwilight) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#e2c47e")
}

func (t *TintTwilight) Black() lipgloss.Color {
	return lipgloss.Color("#141414")
}

func (t *TintTwilight) Blue() lipgloss.Color {
	return lipgloss.Color("#44474a")
}

func (t *TintTwilight) Cyan() lipgloss.Color {
	return lipgloss.Color("#778385")
}

func (t *TintTwilight) Green() lipgloss.Color {
	return lipgloss.Color("#afb97a")
}

func (t *TintTwilight) Purple() lipgloss.Color {
	return lipgloss.Color("#b4be7c")
}

func (t *TintTwilight) Red() lipgloss.Color {
	return lipgloss.Color("#c06d44")
}

func (t *TintTwilight) White() lipgloss.Color {
	return lipgloss.Color("#ffffd4")
}

func (t *TintTwilight) Yellow() lipgloss.Color {
	return lipgloss.Color("#c2a86c")
}
