// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintVibrantInk (VibrantInk) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=VibrantInk
type TintVibrantInk struct{}

// DisplayName returns the display name of the tint.
func (t *TintVibrantInk) DisplayName() string {
	return "VibrantInk"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintVibrantInk) ID() string {
	return "vibrant_ink"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintVibrantInk) About() string {
	return `Tint: VibrantInk`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintVibrantInk) Fg() lipgloss.Color {
	return lipgloss.Color("#ffffff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintVibrantInk) Bg() lipgloss.Color {
	return lipgloss.Color("#000000")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintVibrantInk) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintVibrantInk) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintVibrantInk) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#555555")
}

func (t *TintVibrantInk) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#0000ff")
}

func (t *TintVibrantInk) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#00ffff")
}

func (t *TintVibrantInk) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#00ff00")
}

func (t *TintVibrantInk) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#ff00ff")
}

func (t *TintVibrantInk) BrightRed() lipgloss.Color {
	return lipgloss.Color("#ff0000")
}

func (t *TintVibrantInk) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#e5e5e5")
}

func (t *TintVibrantInk) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#ffff00")
}

func (t *TintVibrantInk) Black() lipgloss.Color {
	return lipgloss.Color("#878787")
}

func (t *TintVibrantInk) Blue() lipgloss.Color {
	return lipgloss.Color("#44b4cc")
}

func (t *TintVibrantInk) Cyan() lipgloss.Color {
	return lipgloss.Color("#44b4cc")
}

func (t *TintVibrantInk) Green() lipgloss.Color {
	return lipgloss.Color("#ccff04")
}

func (t *TintVibrantInk) Purple() lipgloss.Color {
	return lipgloss.Color("#9933cc")
}

func (t *TintVibrantInk) Red() lipgloss.Color {
	return lipgloss.Color("#ff6600")
}

func (t *TintVibrantInk) White() lipgloss.Color {
	return lipgloss.Color("#f5f5f5")
}

func (t *TintVibrantInk) Yellow() lipgloss.Color {
	return lipgloss.Color("#ffcc00")
}
