// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by tintgen. DO NOT EDIT.
//
// Generated using tints/themes from:
//  * https://github.com/atomcorp/themes

package tints

import (
	"github.com/charmbracelet/lipgloss"
)

// TintWildCherry (WildCherry) is a collection of lipgloss styles.
//
// Reference: https://windowsterminalthemes.dev/?theme=WildCherry
type TintWildCherry struct{}

// DisplayName returns the display name of the tint.
func (t *TintWildCherry) DisplayName() string {
	return "WildCherry"
}

// ID returns the name of the tint (normalized, snakecase style).
func (t *TintWildCherry) ID() string {
	return "wild_cherry"
}

// About returns information about the tint (and if we have credit for who
// assisted with/created it).
func (t *TintWildCherry) About() string {
	return `Tint: WildCherry`
}

// Fg returns the recommended default foreground color for this tint.
func (t *TintWildCherry) Fg() lipgloss.Color {
	return lipgloss.Color("#dafaff")
}

// Bg returns the recommended default background color for this tint.
func (t *TintWildCherry) Bg() lipgloss.Color {
	return lipgloss.Color("#1f1726")
}

// SelectionBg returns the recommended background color for selected text.
func (t *TintWildCherry) SelectionBg() lipgloss.Color {
	return lipgloss.Color("")
}

// Cursor returns the recommended color for the cursor.
func (t *TintWildCherry) Cursor() lipgloss.Color {
	return lipgloss.Color("")
}

func (t *TintWildCherry) BrightBlack() lipgloss.Color {
	return lipgloss.Color("#009cc9")
}

func (t *TintWildCherry) BrightBlue() lipgloss.Color {
	return lipgloss.Color("#308cba")
}

func (t *TintWildCherry) BrightCyan() lipgloss.Color {
	return lipgloss.Color("#ff919d")
}

func (t *TintWildCherry) BrightGreen() lipgloss.Color {
	return lipgloss.Color("#f4dca5")
}

func (t *TintWildCherry) BrightPurple() lipgloss.Color {
	return lipgloss.Color("#ae636b")
}

func (t *TintWildCherry) BrightRed() lipgloss.Color {
	return lipgloss.Color("#da6bac")
}

func (t *TintWildCherry) BrightWhite() lipgloss.Color {
	return lipgloss.Color("#e4838d")
}

func (t *TintWildCherry) BrightYellow() lipgloss.Color {
	return lipgloss.Color("#eac066")
}

func (t *TintWildCherry) Black() lipgloss.Color {
	return lipgloss.Color("#000507")
}

func (t *TintWildCherry) Blue() lipgloss.Color {
	return lipgloss.Color("#883cdc")
}

func (t *TintWildCherry) Cyan() lipgloss.Color {
	return lipgloss.Color("#c1b8b7")
}

func (t *TintWildCherry) Green() lipgloss.Color {
	return lipgloss.Color("#2ab250")
}

func (t *TintWildCherry) Purple() lipgloss.Color {
	return lipgloss.Color("#ececec")
}

func (t *TintWildCherry) Red() lipgloss.Color {
	return lipgloss.Color("#d94085")
}

func (t *TintWildCherry) White() lipgloss.Color {
	return lipgloss.Color("#fff8de")
}

func (t *TintWildCherry) Yellow() lipgloss.Color {
	return lipgloss.Color("#ffd16f")
}
