name: renovate

on:
  workflow_dispatch:
    inputs:
      force-run:
        description: >-
          Force a run regardless of the schedule configuration.
        required: false
        default: false
        type: boolean
  push:
    branches: [master]
  schedule:
    - cron: "0 5 1,15 * *"

jobs:
  renovate:
    uses: lrstanley/.github/.github/workflows/renovate.yml@master
    secrets: inherit
    with:
      force-run: ${{ inputs.force-run == true || github.event_name == 'schedule' }}
